### ISSUE TITLE
cannot start

### ISSUE THREAD

**Issue by thiegoskip10** [pizzaboxer/bloxstrap#2501] opened 2024-07-28 00:08 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

System.InvalidOperationException: Cannot start process because a file name has not been provided.

**Comment by pizzaboxer** [comment] 2024-07-28 19:52
Can you send the log file please?

**Comment by pizzaboxer** [comment] 2024-07-29 16:18
Duplicate of #2315
If you're trying to find out why Roblox isn't launching, see https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

**Closed by pizzaboxer** 2024-07-29 16:18 UTC
