### ISSUE TITLE
Suspicion of a Bitcoin Miner.

### ISSUE THREAD

**Issue by Wapplee** [pizzaboxer/bloxstrap#684] opened 2023-09-17 03:56 UTC
Only when i have it installed, my pc overheats and bluescreens. I have been problems with this ever since i installed it, if you are having same problems, just uninstall.

**Comment by OrphanObliterator** [comment] 2023-09-17 05:59
it is not a bitcoin miner

**Comment by GoingCrazyDude** [comment] 2023-09-17 06:02
Yeah its a open source bitcoin miner, please don't download!
But seriously, its literally open source. You can check the source code. There is no mention or use of a bitcoin miner as you suggest.
Maybe you should stop trying to play roblox on a shitty computer instead.

**Comment by Sahelantrophus** [comment] 2023-09-17 11:11
check the source code, it's not a bitcoin miner, maybe try not running it on your pentium 3

**Comment by PrivateDataStorage** [comment] 2023-09-17 11:14
> Only when i have it installed, my pc overheats and bluescreens. I have been problems with this ever since i installed it, if you are having same problems, just uninstall.

maybe you should check out your pc specs first before making claims

**Comment by Sahelantrophus** [comment] 2023-09-17 11:45
https://github.com/pizzaboxer/bloxstrap/assets/135360571/7e281c25-8e79-4bde-a8aa-d8fd260c98e8

**Comment by pizzaboxer** [comment] 2023-09-17 11:55
This could be for any number of reasons, but your first assumption is it being a bitcoin miner? Okay then. Anyway, a few things:

- When it was heating up, did you ever open Task Manager to see what was actually using up all your system resources? That's an important thing to know before you just accuse my software of being a Bitcoin miner.
- What Stop code does the BSOD show? Would help to clear up if it's resource exhaustion, or something caused by Roblox, or even .NET.
- What options do (or did) you have configured in the FastFlags section of the menu? Looking at that would help clear up why your PC overheats.
- What are the specs of your PC? If they really are that bad, that could possibly explain something.

**Comment by WaviestBalloon** [comment] 2023-09-17 15:16
Wrong

**Comment by Wapplee** [comment] 2023-09-17 15:37
> Yeah its a open source bitcoin miner, please don't download! But seriously, its literally open source. You can check the source code. There is no mention or use of a bitcoin miner as you suggest. Maybe you should stop trying to play roblox on a shitty computer instead.

Why don't you quit making assumptions that i have a "shitty computer" and check out your own. I probably have better specs anyway. Why are you so offended by my issue? If you want to  say such negative things how about you go somewhere else and find someone to hate on.

**Comment by Mugetsu895** [comment] 2023-09-17 15:45
> > Yeah its a open source bitcoin miner, please don't download! But seriously, its literally open source. You can check the source code. There is no mention or use of a bitcoin miner as you suggest. Maybe you should stop trying to play roblox on a shitty computer instead.
> 
> Why don't you quit making assumptions that i have a "shitty computer" and check out your own. I probably have better specs anyway. Why are you so offended by my issue? If you want to say such negative things how about you go somewhere else and find someone to hate on.

just reply to the author's message if you want to actually get support

**Comment by GoingCrazyDude** [comment] 2023-09-17 15:46
> > Yeah its a open source bitcoin miner, please don't download! But seriously, its literally open source. You can check the source code. There is no mention or use of a bitcoin miner as you suggest. Maybe you should stop trying to play roblox on a shitty computer instead.
> 
> Why don't you quit making assumptions that i have a "shitty computer" and check out your own. I probably have better specs anyway. Why are you so offended by my issue? If you want to say such negative things how about you go somewhere else and find someone to hate on.

Maybe don't accuse it of being malware?

**Comment by PrivateDataStorage** [comment] 2023-09-17 15:53
> > Yeah its a open source bitcoin miner, please don't download! But seriously, its literally open source. You can check the source code. There is no mention or use of a bitcoin miner as you suggest. Maybe you should stop trying to play roblox on a shitty computer instead.
> 
> Why don't you quit making assumptions that i have a "shitty computer" and check out your own. I probably have better specs anyway. Why are you so offended by my issue? If you want to say such negative things how about you go somewhere else and find someone to hate on.

quite ironic as ur hating on bloxstrap for being a "bitcoin miner"

**Comment by WaviestBalloon** [comment] 2023-09-17 16:41
https://github.com/pizzaboxer/bloxstrap/assets/31796727/e960c575-157f-4b5a-b00a-5270bca1d9a8

**Comment by pizzaboxer** [comment] 2023-09-19 09:58
Closing, since it's been 24 hours since OP last replied, which makes me certain this is just some dude trolling.

**Closed by pizzaboxer** 2023-09-19 09:58 UTC
