### ISSUE TITLE
[BUG] Cant play more than 10 mins without it freezing my pc.

### ISSUE THREAD

**Issue by genstarhimms** [pizzaboxer/bloxstrap#839] opened 2023-10-27 02:25 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Every time i load into a game i either crash after 30 seconds or after 10 minutes, i have tried numerous ways of trying to fix this but nothing works.
- when my game freezes all background noises stay playing but my windows key and alt-F4 don't work, and the only way to back out of the freeze is to turn off my pc manually. It is almost like the game is running normally but a new frame appears every 2-4 seconds.

Any support would be greatly appreciated, Thank you :)

**Comment by pizzaboxer** [comment] 2023-10-27 08:48
Does it happen without? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by WaviestBalloon** [comment] 2023-10-27 10:15
This might be a dupe of https://github.com/pizzaboxer/bloxstrap/issues/835 as multiple people are experiencing the same issue.
Check https://github.com/pizzaboxer/bloxstrap/issues/828 as well.

**Comment by BokBoy** [comment] 2023-11-06 23:38
@genstarhimms, this might sound like not the problem but PC specs please?? Also, what version of windows??

**Comment by pizzaboxer** [comment] 2023-12-01 19:27
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Closed by pizzaboxer** 2023-12-01 19:27 UTC
Labels: clarification needed
