### ISSUE TITLE
[REQ] Small warning when adding custom fonts via the app

### ISSUE THREAD

**Issue by BlueOutside** [pizzaboxer/bloxstrap#2830] opened 2024-09-05 21:25 UTC
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

AFAIK, adding a custom font with the app will overwrite all of the fonts with the selected font.
Tho the inconvenient is the font is the same one for the different versions such as bold, italic, semi-bold etc...
What i mean by that is if something needs bold, it may not be bold, if its in italic, it wont be in italic etc...
I suggest adding a small warning prompting users to either

A. Download a font from the mods forum of the server as it may have variantes of the font like Bold, Extra bold etc thus having maximum support

B. Download a variable font (which should adapt itself automatically)

C. (For experienced users ig) Download the font and it's variantes and then add the files manually

D. (As a last resort/If the font is big) Use the font resizing fflag to properly adjust their font)

Before adding a custom font

**Comment by pizzaboxer** [comment] 2024-09-06 22:25
Duplicate of #2804

**Closed by pizzaboxer** 2024-09-06 22:25 UTC
