### ISSUE TITLE
[BUG] the escape menu is not working alt f4 doesnt work too i need to go to task manager to end the task

### ISSUE THREAD

**Issue by ErikaXGH** [pizzaboxer/bloxstrap#2917] opened 2024-09-19 21:13 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

please fix this

### Bloxstrap Log

N/A

**Comment by moosetwin0** [comment] 2024-09-19 21:23
This is a duplicate of #2911, I recommend closing and talking there.

**Comment by laprium** [comment] 2024-09-20 08:07
yeah i have that problem and i didnt know i was scared that my computer wont leave or the game trapped me

**Closed** 2024-09-20 16:39 UTC
