### ISSUE TITLE
[REQ] Add an option to change your death sound.

### ISSUE THREAD

**Issue by LVIENG** [pizzaboxer/bloxstrap#2879] opened 2024-09-13 01:39 UTC
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Add an option somewhere to change your death sound to a different sound. If I try to do it on my own, it simply just replaces it with the death sound again.

**Comment by B00ie23** [comment] 2024-09-13 20:11
On the Bloxstrap menu, go to the Mods section and open the mods folder. In the explorer window, look for `content` → `sounds`. If the `sounds` folder doesn't exist, create the folder with that name.

Next, in the folder, paste the sound you want as your death sound, then rename it to `ouch.ogg`.
[Note: It doesn't matter what format the sound was exported as initially (wav, ogg, mp3,) as long as the file name is specifically `ouch.ogg`, the client will play it.]

But yeah, I upvote. An option to change the other sounds (jumping, footsteps, falling,) would make this faster as I can just tell Bloxstrap go to a specific folder for all the sounds.

**Comment by pizzaboxer** [comment] 2024-09-15 17:36
> If I try to do it on my own, it simply just replaces it with the death sound again.

Because you have the preset for it enabled.

Duplicate of #1348

**Closed by pizzaboxer** 2024-09-15 17:36 UTC
