### ISSUE TITLE
[REQ] game specific preferred lighting technology

### ISSUE THREAD

**Issue by IMrCreepyI** [pizzaboxer/bloxstrap#1868] opened 2024-05-27 19:37 UTC
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

no clue if this would even be possible. but it would be nice to be able to have a way to add games to have a certain lighting technology and not have that be default for all games

**Comment by pizzaboxer** [comment] 2024-06-08 21:21
Duplicate of #1098

**Closed by pizzaboxer** 2024-06-08 21:21 UTC
Labels: enhancement
