### ISSUE TITLE
Constant Kicking due to "Unexpected Client Behaviour."

### ISSUE THREAD

**Issue by mystic-akito** [pizzaboxer/bloxstrap#193] opened 2023-05-04 20:17 UTC
Whenever I try to join a game experience, any game experience, with the newest version of Bloxstrap (v2.3.0) I get an error that says "You have been kicked due to unexpected client behavior." What should I do?

**Comment by pizzaboxer** [comment] 2023-05-04 20:20
Uninstall Bloxstrap to revert back to the original bootstrapper, and check if it's still happening. I have a feeling this isn't Bloxstrap related, so check to make sure if it still happens without it.

**Comment by mystic-akito** [comment] 2023-05-04 20:23
Huh. It's happening with the original Roblox Player as well. Weird.

**Comment by pizzaboxer** [comment] 2023-05-04 20:23
Oh, I'm actually experiencing this myself too. Huh? Hold on, let me check if this still happens without Bloxstrap.

![image](https://user-images.githubusercontent.com/41478239/236320766-8af9fb99-80cb-401c-83b4-60ed5991133e.png)

**Comment by carter0nline** [comment] 2023-05-04 20:23
Having the same issue.

**Comment by SmallSmallXD** [comment] 2023-05-04 20:25
Same

**Comment by pizzaboxer** [comment] 2023-05-04 20:25
...it's still happening without Bloxstrap being installed. Huh? Did Roblox just colossally screw up or something?

![image](https://user-images.githubusercontent.com/41478239/236321204-e939f61a-6266-4c63-9dbe-f5b32d437491.png)

**Comment by honkaiimpact3rd** [comment] 2023-05-04 20:26
Uninstalled Bloxstrap and reinstalled Roblox, but the issue is sitll happening. Is it really a Bloxstrap issue???

**Comment by mystic-akito** [comment] 2023-05-04 20:26
Well, one of my friends told me to clear out `%localappdata%\Roblox`, so maybe try doing that?

**Comment by pwsf2** [comment] 2023-05-04 20:26
i uninstalled bloxstrap and i'm not getting the error anymore

**Comment by carter0nline** [comment] 2023-05-04 20:27
@pizzaboxer Try with Bloxstrap uninstalled & a Roblox reinstall maybe?

**Comment by pizzaboxer** [comment] 2023-05-04 20:28
Okay, I just tried joining a game again and it works now. Reinstalling Bloxstrap right now.

**Comment by SmallSmallXD** [comment] 2023-05-04 20:28
Cleared %localappdata%/roblox fixed it

**Comment by pizzaboxer** [comment] 2023-05-04 20:29
Okay, I'm in a game now. Definitely not a Bloxstrap related cause.

![image](https://user-images.githubusercontent.com/41478239/236322127-6c097b4b-8979-4497-bd3f-e7df770c0b44.png)

**Comment by SpazElectro** [comment] 2023-05-04 20:32
All works for me.

**Comment by carter0nline** [comment] 2023-05-04 20:33
Downdetector and Twitter both indicate this is probably a Roblox-wide issue

**Comment by pizzaboxer** [comment] 2023-05-04 20:35
Oh sweet, this really is just a "Roblox colossally fucked up" moment. I guess I should've checked before. Guess we'll just have to wait it out. Marking this as resolved.

![image](https://user-images.githubusercontent.com/41478239/236323076-669455eb-542a-415e-a90d-3d5f79beff69.png)

**Comment by mystic-akito** [comment] 2023-05-04 20:35
Oh, I didn't expect that would happen due to the Outage. Huh.

**Closed by pizzaboxer** 2023-05-04 20:35 UTC
Labels: critical
