### ISSUE TITLE
System.Invalid

### ISSUE THREAD

**Issue by lukaseds** [pizzaboxer/bloxstrap#2514] opened 2024-07-29 14:06 UTC
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

System.InvalidOperationException: Cannot start process because a file name has not been provided.
and how to fix it?

**Comment by pizzaboxer** [comment] 2024-07-29 16:06
Can you send the log file please?

**Comment by lukaseds** [comment] 2024-07-29 16:09
[Bloxstrap_20240729T160909Z.log](https://github.com/user-attachments/files/16416008/Bloxstrap_20240729T160909Z.log)

**Comment by pizzaboxer** [comment] 2024-07-29 16:18
Duplicate of #2315
If you're trying to find out why Roblox isn't launching, see https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

**Closed by pizzaboxer** 2024-07-29 16:18 UTC
