### ISSUE TITLE
[FEATURE REQUEST] Revert back to old buttons

### ISSUE THREAD

**Issue by Razor7100** [pizzaboxer/bloxstrap#986] opened 2023-11-26 21:22 UTC
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Can you make a toggle to revert back to the old buttons? on alot of games it breaks the games custom buttons
![image](https://github.com/pizzaboxer/bloxstrap/assets/121650332/ce54f049-e4c4-42cd-bfca-f9eec4efa1b8)

**Comment by TheMetalTechnet** [comment] 2023-11-26 21:32
There's a FFlag for it (which I don't remember), but most than certainly pizzaboxer will add a toggle for it

**Comment by Razor7100** [comment] 2023-11-26 21:37
Yeah i cant find it anywhere & i havent figured out fastflag stuff yet and its easier just for a toggle

**Comment by TheMetalTechnet** [comment] 2023-11-26 21:47
```
{"FFlagEnableInGameMenuChrome": "True"}
```

**Comment by pizzaboxer** [comment] 2023-11-26 21:48
Duplicate of #984 960

**Closed by pizzaboxer** 2023-11-26 21:48 UTC
