### ISSUE TITLE
Loader 

### ISSUE THREAD

**Issue by Razor7100** [pizzaboxer/bloxstrap#114] opened 2023-03-16 22:33 UTC
the loader is bugged and then a blue line shows up in the side its a square
![image](https://user-images.githubusercontent.com/121650332/225767773-2de1c10b-057b-4582-bf99-95c1039e435d.png)

**Comment by Razor7100** [comment] 2023-03-16 22:33
not sure how to explain it good sorry

**Comment by pizzaboxer** [comment] 2023-03-16 22:46
Duplicate of #96.

**Closed by pizzaboxer** 2023-03-16 22:46 UTC
