### ISSUE TITLE
[BUG]  im having an issue about menu escape

### ISSUE THREAD

**Issue by laprium** [pizzaboxer/bloxstrap#2914] opened 2024-09-19 20:26 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I do have a big issue, is when i'm trying to leave i cant see anything only settings but i cant go on it or try to tab, i need to go on the Task Manager To close it and i wanna stop that because i know only The way to leave normally and not using anything.
![Screen Shot-202419092224](https://github.com/user-attachments/assets/3c887c7e-afa4-4749-a221-1b33fdd08d7e)

### Bloxstrap Log

N/A

**Comment by moosetwin0** [comment] 2024-09-19 21:02
Also having this issue.

**Comment by VeryCoolGuy-TSC** [comment] 2024-09-19 21:04
im having this issue aswell.

**Comment by SilverT4** [comment] 2024-09-19 21:04
Roblox seems to have pushed a new update recently that (likely unintentionally) breaks the 2015 escape menu. For now, just use the 2023 one.
![RobloxScreenShot20240919_170257413](https://github.com/user-attachments/assets/5b2fdea6-295b-421a-87d8-e178815f84fe)

**Comment by moosetwin0** [comment] 2024-09-19 21:06
This is a duplicate of #2911, I recommend closing and talking there.

**Comment by CharlesLec2018** [comment] 2024-09-20 13:35
I also got the issue i cant leave the game and close the roblox so to leave or to close i have to turn off my connection

**Closed** 2024-09-20 16:39 UTC

**Comment by laprium** [comment] 2024-09-20 16:41
I did everything and it works thank everyone
