### ISSUE TITLE
[REQ] Enable or Disable feature for fast flags

### ISSUE THREAD

**Issue by RuthlessVerizon** [pizzaboxer/bloxstrap#2874] opened 2024-09-11 15:15 UTC
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

please add an enable or disable feature for fast flags as for some fast flags you may need at one time and not at the other. it can become handy

**Comment by RuthlessVerizon** [comment] 2024-09-11 15:57
> you can add _PlaceFilter

how does that work?

**Comment by NabHeyka22** [comment] 2024-09-11 16:05
flagname_PlaceFilter: value;placeid

**Comment by pizzaboxer** [comment] 2024-09-15 17:47
Duplicate of #1098 (to an extent)

**Closed by pizzaboxer** 2024-09-15 17:47 UTC
