### ISSUE TITLE
Windows Defender flags Bloxstrap as malicious

### ISSUE THREAD

**Issue by AVeryBrokenNPC** [pizzaboxer/bloxstrap#456] opened 2023-07-26 16:06 UTC
![image](https://github.com/pizzaboxer/bloxstrap/assets/95186111/fae55522-dd01-48af-8c0d-a1f0942330a2)
A temporary fix for this is 1. disabling Windows Defender 2. adding bloxstrap install folder to exclusions

**Comment by xM4rkHUN** [comment] 2023-07-26 16:07
dw
we cant do anything with that name

**Comment by pizzaboxer** [comment] 2023-07-26 16:08
duplicate of #454

**Closed by pizzaboxer** 2023-07-26 16:08 UTC
