### ISSUE TITLE
[BUG] you cant reset or leave because the ui dissapears

### ISSUE THREAD

**Issue by hashgambler** [pizzaboxer/bloxstrap#2995] opened 2024-09-28 20:11 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

i was randomly playing one day until i saw that i couldn't leave or reset and everything was gone
![Screenshot 2024-09-28 155914](https://github.com/user-attachments/assets/ef9de160-736f-48ca-a72e-040eed5c09dc)

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment] 2024-09-28 20:13
Here we go again.
Add this fflag
{
  "FFlagFixReportButtonCutOff": "False"
}
If it doesn't work, use another menu like the 2023 one.

**Comment by SilverNugget56** [comment] 2024-09-28 20:26
I can't even use task manager to close out so I have to restart my in order to close roblox

**Comment by NabHeyka22** [comment] 2024-09-28 20:42
> I can't even use task manager to close out so I have to restart my in order to close roblox

Read above what i said.

**Comment by pizzaboxer** [comment] 2024-09-28 20:55
Duplicate of #2911

**Closed by pizzaboxer** 2024-09-28 20:55 UTC
