### ISSUE TITLE
[BUG] Roblox never finishes "configuring" whenever I have the "Force ROBLOX Reinstallation" option enabled.

### ISSUE THREAD

**Issue by bluuboi123** [pizzaboxer/bloxstrap#2469] opened 2024-07-24 06:00 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Each time I try booting up ROBLOX with the option "Force ROBLOX Reinstallation" on it just gets stuck on "Configuring..." and I can't even play it now. There is also no option to disable the option until it actually reinstalls ROBLOX I'm guessing? I had to try this in the first place because of another bug where the "Custom font" feature wouldn't go back to normal even after taking out the custom font.

**Comment by pizzaboxer** [comment] 2024-07-28 19:36
Duplicate of #2199

**Closed by pizzaboxer** 2024-07-28 19:36 UTC
