### ISSUE TITLE
[BUG] Low quality escape menu

### ISSUE THREAD

**Issue by PeekoYT** [pizzaboxer/bloxstrap#2322] opened 2024-07-11 22:36 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

The game looks great, runs great, and my RAM is optimized, yet the escape menu is low quality. I also have my texture quality all the way up so I don't know why this would be happening.

**Comment by Danissohandsome** [comment] 2024-07-11 23:44
Same thing happening to me, I tried deinstalling an reinstalling Roblox, didn't work. When I try to set the graphics its stuck with the graphic levels I had setup yesterday, so basically I'm stuck at high graphs.

**Comment by pizzaboxer** [comment] 2024-07-15 07:01
Duplicate of #2321

**Closed by pizzaboxer** 2024-07-15 07:01 UTC
