### ISSUE TITLE
[BUG] Advanced Graphic Selector not working.

### ISSUE THREAD

**Issue by SxpS1** [pizzaboxer/bloxstrap#2820] opened 2024-09-04 23:55 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

The graphic levels stay at 10, no matter what i do on the bloxstrap menu. It was working perfecly fine till yesterday, i tried playing today and the graphics just go to 10, and not 21.

**Comment by FloofyBoiFieldy** [comment] 2024-09-05 01:00
I also have this issue, happened after a roblox update. So, I am assuming that what caused it.

**Comment by Khookins** [comment] 2024-09-05 01:10
i have also encountered this issue, i went to double check the setting was enabled and it was. I even used the  "Restart Fresh On Next Launch" To See if That Would fix it, which it didn't. Please Fix This.

**Comment by gaming18192** [comment] 2024-09-05 01:36
look at issue #2812, roblox removed the fflag and its going to be removed in the next launcher update

**Comment by spokeys06** [comment] 2024-09-05 16:25
it not wokring for me too it stuck at 10 instead of 21 during configure

**Comment by pizzaboxer** [comment] 2024-09-06 22:18
Duplicate of #2812

**Closed by pizzaboxer** 2024-09-06 22:18 UTC
