### ISSUE TITLE
System.ComponentModel.Win32Exception: Not enough quota is available to process this command.

### ISSUE THREAD

**Issue by AhmadNoty** [pizzaboxer/bloxstrap#1274] opened 2024-02-09 17:39 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

**I right-clicked Bloxstrap in the system tray and this error occurred:**
System.ComponentModel.Win32Exception: Not enough quota is available to process this command.

**log file:**
[Bloxstrap_14450728T105630Z.log](https://github.com/pizzaboxer/bloxstrap/files/14224690/Bloxstrap_14450728T105630Z.log)

**Comment by pizzaboxer** [comment] 2024-02-09 18:59
A few questions here:
- Is this happening every time you try to right-click on it, or did it just happen once?
- Was Roblox still open when you tried clicking it?

**Comment by pizzaboxer** [comment] 2024-02-12 09:28
Alright, I'm not too concerned if this only happened once, as this is a known one-off issue that we are working on fixing in a future version. You don't have to worry much.

Duplicate of #788

**Closed by pizzaboxer** 2024-02-12 09:28 UTC
