### ISSUE TITLE
[REQ] Add a restore to default button in flags editor tab

### ISSUE THREAD

**Issue by roblosplaya** [pizzaboxer/bloxstrap#3007] opened 2024-09-29 21:14 UTC
### Acknowledgement of preliminary instructions

- [x] I have read and acknowledged the preliminary instructions.

### What idea do you have?

removes all added flags and restores preset flags to default

**Comment by Mugetsu895** [comment] 2024-09-29 21:25
I swear this was suggested before 🤔

**Comment by Mugetsu895** [comment] 2024-09-29 21:26
https://github.com/pizzaboxer/bloxstrap/issues/2865#issue-2514681390

**Comment by roblosplaya** [comment] 2024-09-29 21:40
ok

**Comment by roblosplaya** [comment] 2024-09-29 21:40
> [#2865 (comment)](https://github.com/pizzaboxer/bloxstrap/issues/2865#issue-2514681390)

ok

**Comment by pizzaboxer** [comment] 2024-10-01 10:13
Duplicate of #2865

**Closed by pizzaboxer** 2024-10-01 10:13 UTC
