### ISSUE TITLE
[BUG] new roblox ui glitched the ui setting and no longer uses the ui u choose

### ISSUE THREAD

**Issue by welcometogithub23** [pizzaboxer/bloxstrap#965] opened 2023-11-21 16:53 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

new roblox ui glitched the ui setting and no longer uses the ui u choose

**Comment by pizzaboxer** [comment] 2023-11-21 18:31
Duplicate of #960

**Closed by pizzaboxer** 2023-11-21 18:31 UTC
