### ISSUE TITLE
[BUG] All Roblox Menus Not Working (Except for 2024 Menu)

### ISSUE THREAD

**Issue by TimMarvelHero** [pizzaboxer/bloxstrap#2944] opened 2024-09-21 18:15 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Whenever I want to leave a game it doesn't let me, it just shows up with an opaque gray window, even if I press Alt F4 or try close Roblox through windowed mode to close the window I am always forced to to use Task Manager to close Roblox whenever I want to leave, sometimes Roblox just doesn't appear in Task Manager and I need to restart my computer and whenever I open the Roblox menu the everything is gone except for Reset Character, Leave and Resume, this happened to all menus I tested except for the 2024 one which didn't have these issues, since this has become a problem and has been persisting several times I am forced to use the current 2024 menu. I hope this will be fixed.

### Bloxstrap Log

N/A

**Comment by bluepilledgreat** [comment] 2024-09-21 18:20
Duplicate of other issues

**Closed by bluepilledgreat** 2024-09-21 18:20 UTC
