### ISSUE TITLE
[BUG] Avanced graphics

### ISSUE THREAD

**Issue by parti458777** [pizzaboxer/bloxstrap#2842] opened 2024-09-06 20:43 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

so i opened roblox today as always and when i opened the menu and the avanced graphics option i activated didnt work, i tried to fiz it and nothing i even uninstalled and installed the app again, what i do

**Comment by NabHeyka22** [comment] 2024-09-06 20:44
fflag that made it work got removed
option will be gone next update

**Comment by Storm-930** [comment] 2024-09-06 20:55
uuuuuuuuuuuuuuuuuurgh agaaaaaaaaaaaaain
do the following next time:
- read the preliminary instructions, to be certain your issue isn't already adressed
- read the wiki very well to see if the issue is documented in some form, seeing if said issue isn't known
- use the latest bloxstrap
- READ WHAT THE FUCKING CHECKBOXES DO, SPECIFICALLY THE 4TH, I CANNOT PUT TO WORDS HOW MUCH IT ANGERS ME THAT MOST PEOPLE JUST PUT ALL 4 THINKING IT'S JUST OBLIGATORY TO HAVE ALL 4 TO BE SUPPORTED

**Comment by pizzaboxer** [comment] 2024-09-06 22:34
Duplicate of #2812

**Closed by pizzaboxer** 2024-09-06 22:34 UTC

**Comment by parti458777** [comment] 2024-09-12 01:11
OKAY OKAY I GET IT BRO 😭🙏🙏
