### ISSUE TITLE
I tried bloxstrap for fun on my laptop and now it bricked my laptop. So what do i do now?

### ISSUE THREAD

**Issue by coolman35253** [pizzaboxer/bloxstrap#1144] opened 2024-01-17 10:21 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

What do i do now?

**Comment by pizzaboxer** [comment] 2024-01-18 00:19
What do you mean it bricked your laptop?

**Comment by JustAnEric** [comment] 2024-01-18 00:23
I don't know if that is possible

**Comment by coolman35253** [comment] 2024-01-18 05:34
now my laptop crashes when i play roblox

**Comment by pizzaboxer** [comment] 2024-01-18 11:46
> Now my laptop crashes when i play roblox

What specifically happens? What do you see happening?

> (it's because if bloxstrap)

I can assure you that it's not, and you can confirm that by trying to play Roblox without Bloxstrap. https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by axellse** [comment] 2024-01-18 15:01
I kinda doubt your laptop is "bricked",  if Roblox closes or crashes your laptop is most likely not bricked, it's just Roblox. If you have configured any weird flags then removing them might help.

**Comment by coolman35253** [comment] 2024-01-19 00:47
How do i remove those flags?

**Comment by axellse** [comment] 2024-01-19 06:48
> How do i remove those flags?

If you have added any weird flags you can remove them by removing them in the fastflag editor (Fast flags -> fast flag editor)

If you didn't add any fastflags apart from presets it's just a Roblox issue.

**Comment by pizzaboxer** [comment] 2024-01-19 18:40
> How do i remove those flags?

Before you focus your attention on that, can you check to see if Bloxstrap without Roblox works? I've already told you how to do so.

**Comment by coolman35253** [comment] 2024-01-20 14:23
It's a bloxstrap/roblox problem. I fully wiped roblox and now it's ok.

**Comment by pizzaboxer** [comment] 2024-01-20 14:48
So now does playing Roblox with Bloxstrap work?

**Comment by coolman35253** [comment] 2024-01-20 17:44
The problem is Bloxstrap. I was only trying Bloxstrap for fun and I concluded that I don't need it. And I fixed the problem by fully deleting Roblox, including its local app data.

**Comment by pizzaboxer** [comment] 2024-01-20 18:50
> And I fixed the problem by fully deleting Roblox, including its local app data.

...That means the problem wasn't with Bloxstrap then.

**Comment by coolman35253** [comment] 2024-01-21 01:48
OK 👍

**Comment by coolman35253** [comment] 2024-01-21 08:40
Bloxstrap broke my Roblox

**Comment by pizzaboxer** [comment] 2024-01-21 12:45
> Bloxstrap broke my Roblox.

Did you reinstall Bloxstrap since you closed this?

**Comment by coolman35253** [comment] 2024-01-22 02:14
No, i can't use bloxstrap because it broke my roblox client.

**Comment by pizzaboxer** [comment] 2024-01-22 14:02
If you don't have Bloxstrap installed then it can't be the cause of your issue. You don't still have it installed, do you?

You also still haven't been very clear about what the problem is exactly. Broken in what way? Does Roblox just not launch when you try to launch it? What's happening here?

**Closed** 2024-01-24 07:57 UTC
Labels: not bloxstrap problem

**Comment by JustAnEric** [comment] 2024-01-24 23:22
This seems like an issue with Roblox itself. I have the same problems not with Bloxstrap, but the app itself. I force quit a game and Roblox doesn't open or launch after that. I have to delete registry keys, AppData, temporary folders and so much more in order for Roblox to work again. This is the same with the Microsoft Store version for me.
