### ISSUE TITLE
[BUG] 2015 menu is broken

### ISSUE THREAD

**Issue by githubtestaccountDELETE** [pizzaboxer/bloxstrap#2920] opened 2024-09-19 23:29 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/d12b382c-5469-4c07-8da1-921d347b1f48)

Whenever I go to the menu with bloxstarp, theres nothing. Literally nothing.

### Bloxstrap Log

N/A

**Comment by FruitPunchy0** [comment] 2024-09-19 23:59
Same here. It's specifically broken for the 2015 escape menu. I really hope they patch this

**Comment by moosetwin0** [comment] 2024-09-20 00:20
This is a duplicate of #2911, I recommend closing and talking there.

**Closed** 2024-09-20 00:20 UTC
