### ISSUE TITLE
[REQ] Individual Font Replacement Override in Bloxstrap Menu

### ISSUE THREAD

**Issue by Minecraf75** [pizzaboxer/bloxstrap#2950] opened 2024-09-22 05:00 UTC
### Acknowledgement of preliminary instructions

- [x] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I understand that the Mods folder exists, but it's pretty/very annoying to deal with given my circumstances. It'd be great if in the Bloxstrap menu itself, you could change an individual font or more with different fonts via the UI, the reason is because I've been trying to override Montserrat Extra Bold with Gotham SSm Black since a game I'm working with uses Montserrat Extra Bold with a UI Stroke visual manipulation as a remedy, but I'm sick of it. I've tried everything, even modifying the Montserrat .json file in the game files, but that doesn't work, so it winds up being extremely inconsistent. The game in question is a Tower Defense Simulator fangame by the way, it's an era remake type game, the following footage shows the inconsistencies.

https://github.com/user-attachments/assets/d8a67220-755d-44d4-ba95-22df55bdaf16

As you can notice, the regular and bold[regular] montserrat segments were replaced with Gotham if you pay close attention, but if you look at the Upgrade UI, specifically the tower name, tower level, upgrade name, and the health counter, the montserrat issue persists.

**Comment by pizzaboxer** [comment] 2024-09-27 22:19
Duplicate of #2831

**Closed by pizzaboxer** 2024-09-27 22:19 UTC
Labels: enhancement
