### ISSUE TITLE
[BUG] esc menu not working + not able to directly close app

### ISSUE THREAD

**Issue by ErenFake** [pizzaboxer/bloxstrap#2915] opened 2024-09-19 20:27 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

for whatever reason i cant both close the game (with alt+f4 and esc+l+enter), and the esc menu is not working properly, i mean that i doesnt show players and cant interact with it at all.
i have no idea what is causing the issues and the last time i changed/added a fastflag was 1 week ago
![Screenshot 2024-09-19 200918](https://github.com/user-attachments/assets/2e148d14-c6bc-4ab5-9647-7e16e9918167)

### Bloxstrap Log

N/A

**Comment by moosetwin0** [comment] 2024-09-19 21:04
This is a duplicate of #2914, I recommend closing and talking there.

**Closed** 2024-09-19 21:08 UTC
