### ISSUE TITLE
[REQ] font example when applying font

### ISSUE THREAD

**Issue by xM4rkHUN** [pizzaboxer/bloxstrap#1351] opened 2024-02-26 09:29 UTC
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

When applying font, bloxstrap shows an example of letters or numbers to show what the font will look like. (idk, maybe its unnecessary but i thought it would be cool)

**Comment by pizzaboxer** [comment] 2024-02-26 09:46
Duplicate of #1345

**Closed by pizzaboxer** 2024-02-26 09:46 UTC

**Comment by xM4rkHUN** [comment] 2024-02-26 09:55
> Duplicate of #1345
oh, my bad then
