### ISSUE TITLE
[REQ] shaders

### ISSUE THREAD

**Issue by grubgrubperks** [pizzaboxer/bloxstrap#1186] opened 2024-01-24 19:31 UTC
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

would it be possible to make bloxstrap support nvidea freestyle? doing so would allow the ansel of the graphics card to be used on roblox

**Comment by pizzaboxer** [comment] 2024-01-24 23:32
Duplicate of #997

**Closed by pizzaboxer** 2024-01-24 23:32 UTC

**Comment by grubgrubperks** [comment] 2024-01-25 15:34
mb
