### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Anoynonmous** [pizzaboxer/bloxstrap#1969] opened 2024-06-14 09:15 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.InvalidOperationException: 'ContentControl' TargetType does not match type of element 'DataGridColumnFloatingHeader'.

**Comment by pizzaboxer** [comment] 2024-06-14 12:54
Duplicate of #1231

**Closed by pizzaboxer** 2024-06-14 12:54 UTC
