### ISSUE TITLE
Can I bring back the 2017 top bar from Bloxstrap?

### ISSUE THREAD

**Issue by TehEpikNoobKing** [pizzaboxer/bloxstrap#1487] opened 2024-03-23 16:48 UTC
### Acknowledgement of preliminary instructions

- [x] I have read and acknowledged the preliminary instructions.

### What idea do you have?

How can I possibly get the old 2017 Roblox top bar?

**Comment by pizzaboxer** [comment] 2024-03-23 22:05
Duplicate of #963

**Closed by pizzaboxer** 2024-03-23 22:05 UTC
