### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Katsuhika** [pizzaboxer/bloxstrap#858] opened 2023-10-28 08:05 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Bloxstrap.Exceptions.HttpResponseException: Could not connect to https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zlive because it returned HTTP 401 (Unauthorized)
[Bloxstrap_20231028T080255Z.log](https://github.com/pizzaboxer/bloxstrap/files/13194902/Bloxstrap_20231028T080255Z.log)

**Comment by popbob2** [comment] 2023-10-28 09:28
change your channel to live

**Comment by pizzaboxer** [comment] 2023-10-28 10:36
Duplicate of #857

**Closed by pizzaboxer** 2023-10-28 10:36 UTC
