### ISSUE TITLE
[BUG] Bloxstrap stuck in configuring roblox

### ISSUE THREAD

**Issue by BoxUp23** [pizzaboxer/bloxstrap#3009] opened 2024-09-30 12:53 UTC
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Trying to install Bloxstrap but it is stuck at "Configuring Roblox" screen.
It wont load, I have tried reinstalling it over and over but nothing worked.
![image](https://github.com/user-attachments/assets/c37a5bae-aab1-40dc-9ccc-1dc5c625b54e)

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment] 2024-10-01 10:16
Duplicate of #2673

Please send your latest Bloxstrap log file from `%localappdata%\Bloxstrap\Logs` in that thread

**Closed by pizzaboxer** 2024-10-01 10:16 UTC
