### ISSUE TITLE
[BUG] 2015 Menu bugged

### ISSUE THREAD

**Issue by paperboi31** [pizzaboxer/bloxstrap#3025] opened 2024-10-02 21:55 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

everytime i try and use the 2015 menu, it shows up but the players dont show up, the top buttons dont work (settings reporting etc) leaving the game doesnt work, it brings me to a blank part of the menu with no buttons, please fix this i really like the 2015 menu (also my textures got all blurry?)

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment] 2024-10-02 22:12
Duplicate of #2911

**Closed by pizzaboxer** 2024-10-02 22:12 UTC
