### ISSUE TITLE
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

### ISSUE THREAD

**Issue by Jackcool92** [pizzaboxer/bloxstrap#2716] opened 2024-08-21 21:03 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

![Screenshot 2024-08-21 170000](https://github.com/user-attachments/assets/e13d7e46-3688-4d9c-9d70-5c5b6194eeb1)
 
[Bloxstrap_20240821T205605Z.log](https://github.com/user-attachments/files/16698711/Bloxstrap_20240821T205605Z.log)
I don't know why this is happening, it was working earlier today, I'm not sure how to fix it, please help so i can play normally again.

**Comment by pizzaboxer** [comment] 2024-08-22 11:05
Duplicate of #2704

**Closed by pizzaboxer** 2024-08-22 11:05 UTC
