### ISSUE TITLE
Bloxstrap doesn't clear System Tray icons unless hovered over

### ISSUE THREAD

**Issue by rblxSioFi** [pizzaboxer/bloxstrap#354] opened 2023-07-01 21:37 UTC
This isn't necessarily launcher breaking, but for every instance of Roblox you start (leaving, rejoining, possibly teleporting between games) it drops a new "Bloxstrap" icon into the System Tray.

I'm not sure if this is a Windows 10 specific issue, but I haven't seen any other system tray icon from other apps stay after an application is closed (even if exited by other means other than the system tray).

It might help users to clean up the old system tray icons before creating new ones.

![image](https://github.com/pizzaboxer/bloxstrap/assets/89963996/82401557-7f15-42f3-964c-a2daffcd9593)

https://github.com/pizzaboxer/bloxstrap/assets/89963996/87ba25e3-7eb5-4cc5-b39a-33c20dae1496

**Comment by pizzaboxer** [comment] 2023-07-01 21:39
Duplicate of #295.

**Closed by pizzaboxer** 2023-07-01 21:39 UTC
