### ISSUE TITLE
Discord Rich Presence not working

### ISSUE THREAD

**Issue by warnooob** [pizzaboxer/bloxstrap#24] opened 2022-10-01 07:42 UTC
Just fresh installed the newest version of Bloxstrap, appears that Discord reads my game as the standard Roblox client and not Bloxstrap. I have the feature enabled on the config settings for Bloxstrap and the bootstrapper is clearly running in game (I can tell because of the death sound). However, the Roblox icon on taskbar remains the same, and the Discord game activity just reads "playing a game" with the standard Roblox name and logo.

**Comment by pizzaboxer** [comment] 2022-10-01 08:02
The Roblox icon in the taskbar isn't supposed to change. The game activity I'm not entirely sure of. Are you sure the "Display current activity as a status message" toggle in your Activity Privacy settings isn't disabled?

**Comment by warnooob** [comment] 2022-10-01 08:06
Sure of it. Unsure at what could be causing this but the client doesn't recognize Bloxstrap as a game if that helps

**Comment by pizzaboxer** [comment] 2022-10-01 08:51
I've had this happen to me before sometimes, but rarely, without being able to consistently reproduce it. I'll try and investigate it when I can.

**Comment by Caddy8970** [comment] 2022-10-12 16:07
@pizzaboxer did you find why it doesn't work? It happens to me too.

**Comment by dropier** [comment] 2022-10-15 16:47
it happens to me too.

**Comment by Caddy8970** [comment] 2022-10-17 17:43
Never mind, it works for me

**Comment by pizzaboxer** [comment] 2022-11-11 09:24
Oh, yeah I forgot to update the logic for checking rich presence based on app launching. I'll release v1.5.3 shortly to fix it.

**Comment by purplux** [comment] 2022-11-11 17:19
> Oh, yeah I forgot to update the logic for checking rich presence based on app launching. I'll release v1.5.3 shortly to fix it.

When is this releasing?

**Comment by pizzaboxer** [comment] 2022-11-14 18:53
I've just reworked the rich presence detection system and I'm not sure how relevant this issue is anymore, so I'll close it for now. If I ever notice it happens again, or you guys do, I'll reopen this.

**Closed by pizzaboxer** 2022-11-14 18:53 UTC
Labels: bug
