### ISSUE TITLE
Stuck in 2020 menu version

### ISSUE THREAD

**Issue by ssaltt** [pizzaboxer/bloxstrap#337] opened 2023-06-23 11:40 UTC
Idk if its intentional or not, but when i use the menu, its always on the 2020 version. Even though i have the 2021 version selected.
pls help? the sliders dont work too.

**Comment by lokzz** [comment] 2023-06-23 14:51
check #328

**Comment by pizzaboxer** [comment] 2023-06-23 15:15
Duplicate of #328.

**Closed** 2023-06-23 15:15 UTC
Labels: duplicate
