### ISSUE TITLE
Escape menu V2 not working

### ISSUE THREAD

**Issue by WGYiskool** [pizzaboxer/bloxstrap#2739] opened 2024-08-24 05:54 UTC
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Whenever i save my escape menu to 2022 (V2) it shows me 2015 (V1) in game even though i clearly set it to v2 but 2023 (V4) works fine

**Comment by pizzaboxer** [comment] 2024-08-24 14:51
Duplicate of #2718

**Closed by pizzaboxer** 2024-08-24 14:51 UTC
