### ISSUE TITLE
[BUG] V1 version does not work, I turn it on and there is no list or settings open, you just use esc 3-4 times and everything disappears and roblox cannot close, it only closes through the task manager

### ISSUE THREAD

**Issue by FoxDavid877** [pizzaboxer/bloxstrap#3016] opened 2024-10-01 09:33 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![BUG](https://github.com/user-attachments/assets/9c7f4c9b-c5fb-4d6f-9550-ee426e8161cd)

**Comment by FoxDavid877** [comment] 2024-10-01 09:34
![bug](https://github.com/user-attachments/assets/6d108297-ee45-44e7-a789-24f897bb6d89)

**Comment by pizzaboxer** [comment] 2024-10-01 10:15
Duplicate of #2911

**Closed by pizzaboxer** 2024-10-01 10:15 UTC
