### ISSUE TITLE
req for the new update for '' If you launch Roblox while you're already in a Roblox game, you'll be prompted for confirmation''

### ISSUE THREAD

**Issue by talywrd** [pizzaboxer/bloxstrap#2060] opened 2024-06-16 15:12 UTC
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

*The idea is, make it that you are able to turn this setting off for example, youre in a game afk grinding and you can auto reconnect but that wont work because you have to PRESS ''confirm'' like, you disconnected from the game. **you wont be able to reconnect automatically cause you have to press confirm to launch roblox, so there should be a settings where you can turn this off**

**Comment by talywrd** [comment] 2024-06-16 15:17
Little exmpl: You are in a game afk grinding and having auto reconnect, you disconnected. your auto reconnect won't work because you got to press confirm to launch roblox again.  (it thinks youre in game when you got disconnected)

**Comment by pizzaboxer** [comment] 2024-06-27 09:33
Duplicate of #2011

**Closed by pizzaboxer** 2024-06-27 09:33 UTC
