### ISSUE TITLE
roblox reboots my pc as soon as the program opens.

### ISSUE THREAD

**Issue by farchu7** [pizzaboxer/bloxstrap#644] opened 2023-09-06 03:42 UTC
Several months ago roblox in the windows version stopped working because it restarts only as soon as I open a game. I tried thousands of solutions, and my pc has no problem with any other much heavier game, so it is a problem only with roblox in its version of windows (Because the version of the microsoft store works, although it is a version tedious and incomplete to play). So, i read one of the many forums that I looked for a solution that worked for many, and it was to install bloxstrap, apparently this didn't work for me either and as soon as I open bloxstrap my PC also restarts. Maybe they know something about the restart when opening roblox (Something that happened to many people), or failing that bloxstrap.

I add some basic details.
My PC:
 i3 10105f
Rx550 2gb vram
16GB ram ddr4
Windows 10 (Updated)
Dirext 12
Visual c++ (Updated all)
silver light 5

**Comment by pizzaboxer** [comment] 2023-09-06 09:42
It just... reboots? It doesn't show a blue screen or anything?

**Comment by sdhEmily** [comment] 2023-09-06 10:19
if no bsod is it a psu power draw issue? if i put my camera in a huge clump of particles it draws too much power from my garbage psu and reboots so your game could be drawing huge amounts of power when u start it up

**Comment by pizzaboxer** [comment] 2023-09-06 19:42
I mean, I'll close this since this obviously isn't caused by Bloxstrap in any way. But, I don't mind trying to help you out here.

**Closed by pizzaboxer** 2023-09-06 19:42 UTC
Labels: roblox moment
