### ISSUE TITLE
[BUG] an unexpecter error occurred and roblox needs to quit

### ISSUE THREAD

**Issue by siiiil** [pizzaboxer/bloxstrap#1933] opened 2024-06-07 19:23 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When you have the disable desktop app mod on, as you leave theres an error and it says "An unexpected error occurred and Roblox needs to quit." This is just a nuisance but its just annoying as you have to go to the error and click ok.

**Comment by pizzaboxer** [comment] 2024-06-08 19:58
Duplicate of #1175

**Closed by pizzaboxer** 2024-06-08 19:58 UTC
