### ISSUE TITLE
[BUG] "Bloxstap does not support running in administrator mode. Relaunch or reinstall Bloxstrap with lower privileges."

### ISSUE THREAD

**Issue by MadRacer565** [pizzaboxer/bloxstrap#2004] opened 2024-06-14 22:55 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image_2024-06-14_235051725](https://github.com/pizzaboxer/bloxstrap/assets/85840977/760cf5dd-080a-4a30-bc3e-a58a2bcdf36f)

Randomly had an issue that said 'Bloxstrap does not support running in administrator mode. Relaunch or reinstall Bloxstrap with lower privileges.'
This has never showed up before. So what I did was uninstalled it and reinstalled it to see if it fixed the problem. It has not. Now I can not install it AT ALL and I think it is because I am on a Windows Administrator account. But I have no idea how that would affect the compatibility of Bloxstrap.

**Comment by Jagaziela2** [comment] 2024-06-14 22:56
now?

**Comment by MadRacer565** [comment] 2024-06-14 22:57
Yeah I still cant install it

**Comment by ShadowCodeX-debug** [comment] 2024-06-14 22:57
It was an oversight by Matt, a patch to remove the admin check is being pushed soon.

**Comment by MadRacer565** [comment] 2024-06-14 22:57
Alright, any idea how long that might take?

**Comment by bluepilledgreat** [comment] 2024-06-14 22:58
The check is being removed with v2.6.1. Please be patient, it should release soon.

**Comment by desorz** [comment] 2024-06-14 22:59
can i just download old version of bloxstrap to avoid error until v2.6.1?

**Comment by MiniSquadMini** [comment] 2024-06-14 23:01
Yeah, I never had that issue until 2 minutes ago. I checked compatibility and it doesn't show run with administrator so I reinstalled it at least 3 times, even moving the app out of the downloads folder yet it wouldn't budge.
This bug is really annoying and I hope they patch it because it was not being run in administrator mode and I can not find a way to limit the privileges.

**Comment by desorz** [comment] 2024-06-14 23:04
> Yeah, I never had that issue until 2 minutes ago. I checked compatibility and it doesn't show run with administrator so I reinstalled it at least 3 times, even moving the app out of the downloads folder yet it wouldn't budge. This bug is really annoying and I hope they patch it because it was not being run in administrator mode and I can not find a way to limit the privileges.
> 
> Edit: Small edit, sometimes it works at first launch, desktop app only, but you will be signed out and its hard to trick bloxstrap to work so we can only wait.

i downgraded to v2.5.4 and it works well, just dont use checkbox on "Automatically update Bloxstrap"

**Comment by MinisInDaWall** [comment] 2024-06-14 23:13
> > Yeah, I never had that issue until 2 minutes ago. I checked compatibility and it doesn't show run with administrator so I reinstalled it at least 3 times, even moving the app out of the downloads folder yet it wouldn't budge. This bug is really annoying and I hope they patch it because it was not being run in administrator mode and I can not find a way to limit the privileges.
> > Edit: Small edit, sometimes it works at first launch, desktop app only, but you will be signed out and its hard to trick bloxstrap to work so we can only wait.
> 
> i downgraded to v2.5.4 and it works well, just dont use checkbox on "Automatically update Bloxstrap"

Thanks for the suggestion, this worked out thanks!

**Comment by pizzaboxer** [comment] 2024-06-14 23:21
Duplicate of #2003

**Closed by pizzaboxer** 2024-06-14 23:21 UTC
