### ISSUE TITLE
add a feature to disable the warning because it acounts roblox account manager as a roblox instance and people use it to run multi roblox[REQ] 

### ISSUE THREAD

**Issue by 0uriem** [pizzaboxer/bloxstrap#2012] opened 2024-06-14 23:55 UTC
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Roblox alt manager (roblox account manager) gets flagged as a roblox instance and the warning pops up. its annoying please add a option to disable the warning

**Comment by pizzaboxer** [comment] 2024-06-27 09:33
Duplicate of #2011

**Closed by pizzaboxer** 2024-06-27 09:33 UTC
