### ISSUE TITLE
[REQ] Custom Preset FFlags

### ISSUE THREAD

**Issue by Sxmmer-Time** [pizzaboxer/bloxstrap#1220] opened 2024-02-01 20:03 UTC
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

In the FastFlags Preset area make a way to create custom buttons that edit fastflags kind of like how the FPS one works for example a button that edits the FontSize FInt flag or maybe another flag like SkyGray flag as a button with a true or false value, etc

**Comment by pizzaboxer** [comment] 2024-02-02 00:31
We are already planning to add something like this, but in a different sense. It was partly discussed at #1169 when I was talking about the preset system not being hardcoded and instead being more dynamic. Something I didn't elaborate on there was that if I manage to make it work, I would like for the preset list to be community-sourced so we can easily add useful things when we discover them, like what you're intending for.

I'l close this since this is essentially a duplicate of an idea that we already have, and have already discussed.

**Closed by pizzaboxer** 2024-02-02 00:31 UTC
