### ISSUE TITLE
Some information on Roblox not launching after October 25th

### ISSUE THREAD

**Issue by pizzaboxer** [pizzaboxer/bloxstrap#828] opened 2023-10-26 08:12 UTC
I woke up today to receive a massive influx of reports about Roblox not launching after yesterday anymore. It was bad enough that someone took it upon themselves to try and get my attention through Twitter at 1AM in the morning (please do not do that like ever).

Roblox pushed an update yesterday (on October 25th), and it's evident that this update has made Hyperion's cheat detection even stricter. **This does not have anything to do with Bloxstrap. People who do not use it are having this exact same problem too.** [Four people on the Devforum have reported similar issues following the update](https://devforum.roblox.com/t/roblox-games-load-for-about-3-seconds-then-instantly-crash/2309871/709), and that alone is just people who can post on the DevForum. It is a problem with Roblox.

The best I can do to help you is point you to [this Wiki page](https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch), which I'd at least hope you've already read. 

I will highlight these two specific points though: 

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/450567a7-3f3c-4b50-abc5-f5dab2d8fa53)

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/11455fc5-69ab-4b77-89d6-40a826e6d442)

**Comment by Sepruko** [comment] 2023-10-26 10:57
> is there an estimated time that this will be fixed?

Ask Roblox?

**Comment by DragonKillerz** [comment] 2023-10-26 13:06
> > is there an estimated time that this will be fixed?
> 
> Ask Roblox?

roblox is not affiliated with blox strap so they wont care

**Comment by Sepruko** [comment] 2023-10-26 13:26
> > > is there an estimated time that this will be fixed?
> > 
> > Ask Roblox?
> 
> roblox is not affiliated with blox strap so they wont care

The crashing has nothing to do with Bloxstrap, did you even read the issue?

**Comment by GamingWithShaurya** [comment] 2023-10-26 13:46
Ok it aparently was correct, it was bitdefender Advanced Threat Defense,

which .exe file should i add as exception here for so i can continue to use Bitdefender Threat detection without making it not load roblox?

**Comment by Vezlortix** [comment] 2023-10-26 13:51
> Ok it aparently was correct, it was bitdefender Advanced Threat Defense,
> 
> which .exe file should i add as exception here for so i can continue to use Bitdefender Threat detection without making it not load roblox?

I just opened my pc and i cant join a single game , i although use 2 antiviruses that came with my gaming laptop which are McAfee Including norton despite when i try joining a game , the screen goes white and crashes

**Comment by PNDMARK** [comment] 2023-10-26 14:15
i still dont know how to fix it please help

**Comment by CodingWithAnxiety** [comment] 2023-10-26 14:30
There is currently not a fix. Please play another game for the shortened future.

**Comment by Vezlortix** [comment] 2023-10-26 14:31
Dang man

**Comment by MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM** [comment] 2023-10-26 17:35
this issue is actually annoying because i genuinely stopped every 3rd party services which were running in the background AND apps like discord and everything else besides my browser and i still cant play

**Comment by IxGamerXL** [comment] 2023-10-26 18:18
Pretty typical moderation for Roblox. Either the moderation just doesn't work, or it works in ways that get non-incriminating players clapped in the process.

**Comment by jeswastaken** [comment] 2023-10-26 18:18
i think i found what was bugging it for me, microsoft powertoys peek tool
if it's not that, just close out anything that "injects" into apps in task manager, primarily background apps

**Comment by MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM** [comment] 2023-10-26 22:33
on my end i can't seem to fix it

**Comment by 70T** [comment] 2023-10-26 22:53
Vulkan crashes for me after this update.

**Comment by DragonKillerz** [comment] 2023-10-26 23:36
im not using any antivirus software but i cant join

**Comment by WaviestBalloon** [comment] 2023-10-27 00:12
Currently issues with `version-faaebc838e2e45f6` and `version-7cc666219b484414`, reverting to `version-57e2dd886e0e42a5` *used* to fix it but RCCS is now refusing clients older than newest.

**Comment by WaviestBalloon** [comment] 2023-10-27 00:16
> Vulkan crashes for me after this update.

https://devforum.roblox.com/t/roblox-games-load-for-about-3-seconds-then-instantly-crash/2309871/729?u=waviestballoon

Best to avoid Vulkan right now, Bitdancer has confirmed it trips Hyperion, revert to DirectX (preferably) or OpenGL.

**Comment by user1126s** [comment] 2023-10-27 00:39
Some more information ( this implies to Linux people using custom bootstrapers as well ) 
Source: from vinegarhq discord server, the team behind vinegar, a Linux bootstraper for roblox.
![Screenshot_20231027-060510~2](https://github.com/pizzaboxer/bloxstrap/assets/114283670/b690646e-1aff-46f4-9473-10f4f94c16f8)
![Screenshot_20231027-060608](https://github.com/pizzaboxer/bloxstrap/assets/114283670/5fe45fe2-db1d-4355-bb43-af4b3d7f5d66)

**Comment by user1126s** [comment] 2023-10-27 00:45
https://devforum.roblox.com/t/roblox-games-load-for-about-3-seconds-then-instantly-crash/2309871/ link if you want to open it. (The bug reporter has same pic and specs as me)

**Comment by user1126s** [comment] 2023-10-27 01:04
You can't switch channels or versions, I always stay on zcanary though it lead me to several crashes, switch to live

**Comment by WaviestBalloon** [comment] 2023-10-27 01:23
`zavatarteam2` fixes crashing, it's a rather new deployment as well, try that.

**Comment by 70T** [comment] 2023-10-27 01:41
> > Vulkan crashes for me after this update.
> 
> https://devforum.roblox.com/t/roblox-games-load-for-about-3-seconds-then-instantly-crash/2309871/729?u=waviestballoon
> 
> Best to avoid Vulkan right now, Bitdancer has confirmed it trips Hyperion, revert to DirectX (preferably) or OpenGL. If you change the render API to OpenGL, expect shader issues in-game.

Yeah, but then I can't Game Capture with OBS. Such a well-developed game. Will have to run DX11 windowed mode for now I guess

**Comment by WaviestBalloon** [comment] 2023-10-27 02:25
> > > Vulkan crashes for me after this update.
> > 
> > 
> > https://devforum.roblox.com/t/roblox-games-load-for-about-3-seconds-then-instantly-crash/2309871/729?u=waviestballoon
> > Best to avoid Vulkan right now, Bitdancer has confirmed it trips Hyperion, revert to DirectX (preferably) or OpenGL. If you change the render API to OpenGL, expect shader issues in-game.
> 
> Yeah, but then I can't Game Capture with OBS. Such a well-developed game. Will have to run DX11 windowed mode for now I guess

Try switching to the `zavatarteam2` channel first.

**Comment by WaviestBalloon** [comment] 2023-10-27 10:26
## **Quick recap:**

- The FastFlag to enforce Vulkan rendering can trip Hyperion **(Confirmed by Roblox employee, Bitdancer)**
- Bitdefender has a feature which can trip Hyperion **(Confirmed by Roblox employee, Bitdancer)**
- Issue is not isolated to Roblox on Linux as some people first thought

## **Some possible fixes/solutions:**
- If you are using Bitdefender for your anti-virus provider, **disable "Advanced Threat Defense" or quit out of the application entirely**
- **Do not enforce Roblox to use Vulkan,** switch to DirectX (preferably) or OpenGL (expect shader issues)
- **Force the `zavatarteam2` deployment channel,** fixes crashing for Roblox on Linux users, nobody has confirmed if it works with Windows users yet (please test it if you can)
(https://devforum.roblox.com/t/roblox-games-load-for-about-3-seconds-then-instantly-crash/2309871/731?u=waviestballoon)

**Comment by Ilovecodingasitsfun** [comment] 2023-10-27 11:02
> > Ok it aparently was correct, it was bitdefender Advanced Threat Defense,
> > which .exe file should i add as exception here for so i can continue to use Bitdefender Threat detection without making it not load roblox?
> 
> I just opened my pc and i cant join a single game , i although use 2 antiviruses that came with my gaming laptop which are McAfee Including norton despite when i try joining a game , the screen goes white and crashes

Thats an issue with OpenGL, when I set the rendering to OpenGL it shows white screen then crashes.

**Comment by WaviestBalloon** [comment] 2023-10-27 11:03
@Ilovecodingasitsfun that's expected with OpenGL, Roblox is no longer providing support for it which results in incompatibility and broken shaders, is it possible for you to switch to DirectX?

**Comment by Ilovecodingasitsfun** [comment] 2023-10-27 11:09
> @Ilovecodingasitsfun that's expected with OpenGL, Roblox is no longer providing support for it which results in incompatibility and broken shaders, is it possible for you to switch to DirectX?

I've set it to auto and installed it on to my other drive and it has been working fine ever since.

**Comment by IDDQD1337** [comment] 2023-10-27 14:42
Roblox also started to close for me for 1 minute (and after a couple of seconds), but I found a solution to this problem (at least for me) I just launched Bloxstrap (maybe it will work with a regular client) as administrator

**Comment by 70T** [comment] 2023-10-27 15:31
> > > > Vulkan crashes for me after this update.
> > > 
> > > 
> > > https://devforum.roblox.com/t/roblox-games-load-for-about-3-seconds-then-instantly-crash/2309871/729?u=waviestballoon
> > > Best to avoid Vulkan right now, Bitdancer has confirmed it trips Hyperion, revert to DirectX (preferably) or OpenGL. If you change the render API to OpenGL, expect shader issues in-game.
> > 
> > 
> > Yeah, but then I can't Game Capture with OBS. Such a well-developed game. Will have to run DX11 windowed mode for now I guess
> 
> Try switching to the `zavatarteam2` channel first.

Didn't work for me. Still crashes with Vulkan enabled.

**Comment by WaviestBalloon** [comment] 2023-10-27 19:33
> Roblox also started to close for me for 1 minute (and after a couple of seconds), but I found a solution to this problem (at least for me) I just launched Bloxstrap (maybe it will work with a regular client) as administrator

You should never run the Roblox client or installer with administrative permissions, that isn't much of a fix and isn't recommended.

**Comment by n00bslayerxd** [comment] 2023-10-27 19:42
For the past 2 days I haven't been able to join any game on Roblox's website. Tried using an alt, closing programs, using different renderers, running as administrator, reinstalling Roblox AND Bloxstrap, the crash still happens. I can't even launch the desktop version of Roblox, and when I tried to reinstall Roblox it was stuck on "Starting Roblox..." for about 5 seconds and then just closed itself, but the process was still running. I don't have any crash logs, and I have no idea why this is happening. I'm on Windows and hoping for an update fixing this soon.

**Comment by IxGamerXL** [comment] 2023-10-27 21:52
> > Vulkan crashes for me after this update.
> 
> https://devforum.roblox.com/t/roblox-games-load-for-about-3-seconds-then-instantly-crash/2309871/729?u=waviestballoon
> 
> Best to avoid Vulkan right now, Bitdancer has confirmed it trips Hyperion, revert to DirectX (preferably) or OpenGL.
> If you change the render API to OpenGL, expect shader issues in-game.

Ever since Roblox got a localization-related update, Vulkan ceased to operate at all. I know this because I had my graphics set to Vulkan on the Studio for the sake of performance, and the MOMENT my studio updated; my Studio failed to start up multiple times. This was thankfully avoided on my part after setting the graphics setting back to the default.

Whatever that specific update did, it caused Vulkan to suddenly fail and crash upon use, which almost locked me out of my Studio.

**Comment by WaviestBalloon** [comment] 2023-10-27 22:53
> For the past 2 days I haven't been able to join any game on Roblox's website. Tried using an alt, closing programs, using different renderers, running as administrator, reinstalling Roblox AND Bloxstrap, the crash still happens. I can't even launch the desktop version of Roblox, and when I tried to reinstall Roblox it was stuck on "Starting Roblox..." for about 5 seconds and then just closed itself, but the process was still running. I don't have any crash logs, and I have no idea why this is happening. I'm on Windows and hoping for an update fixing this soon.

Hey can you change your deployment channel to `zavatarteam2` and install that?
It's currently working for Roblox on Linux users and I need to see if it also works for normal Windows users with Bloxstrap.

**Comment by painelle** [comment] 2023-10-28 00:06
using zavatarteam2 doesn't fix it for me 
[Bloxstrap_20231027T122504Z.log](https://github.com/pizzaboxer/bloxstrap/files/13193973/Bloxstrap_20231027T122504Z.log)
logs if it helps

**Comment by user1126s** [comment] 2023-10-28 01:49
> using zavatarteam2 doesn't fix it for me [Bloxstrap_20231028T000714Z.log](https://github.com/pizzaboxer/bloxstrap/files/13193991/Bloxstrap_20231028T000714Z.log) logs if it helps

Probably because it follows diffrent things to be compatible with wine and grapejuice

**Comment by user1126s** [comment] 2023-10-28 01:54
> > Roblox also started to close for me for 1 minute (and after a couple of seconds), but I found a solution to this problem (at least for me) I just launched Bloxstrap (maybe it will work with a regular client) as administrator
> 
> You should never run the Roblox client or installer with administrative permissions, that isn't much of a fix and isn't recommended.

You are right, I don't run them as administrator, I run them as sudo. I have to open the app using terminal with the commands: flatpak run io.github.vinegarhq.Vinegar player --force.
I have to do this 3 times to get it to open for 10 minutes.
I have tried building from source but no change, I also edited the config to change some flags and channels.

**Comment by TacheAdrian542** [comment] 2023-10-28 09:29
Any idea When This will end, About This Incident?

**Comment by n00bslayerxd** [comment] 2023-10-28 09:33
> Hey can you change your deployment channel to `zavatarteam2` and install that? It's currently working for Roblox on Linux users and I need to see if it also works for normal Windows users with Bloxstrap.

Nope, didn't work. Still waiting for Roblox to do something.

**Closed** 2023-10-28 10:52 UTC
Labels: information

**Comment by n00bslayerxd** [comment] 2023-10-28 13:17
> Nope, didn't work. Still waiting for Roblox to do something.

I fixed it. Please look for any potential viruses in your device. I had a miner in my pc.

**Comment by Grizzly1706** [comment] 2023-10-28 15:04
> > Nope, didn't work. Still waiting for Roblox to do something.
> 
> I fixed it. Please look for any potential viruses in your device. I had a miner in my pc.

i don't think data miners have anything to do with a widespread problem that even the developers have acknowledged

**Comment by WaviestBalloon** [comment] 2023-10-28 15:09
> i don't think data miners have anything to do with a widespread problem that even the developers have acknowledged 

People on DevForums are having similar problems, even now related to the installer.

Unsure what is happening at the moment but regarding to client crashing, the team at Roblox has acknowledged the issue but the fix might be slow.

**Comment by user1126s** [comment] 2023-10-28 17:03
> ## **Quick recap:**
> 
>     * The FastFlag to enforce Vulkan rendering can trip Hyperion **(Confirmed by Roblox employee, Bitdancer)**
> 
>     * Bitdefender has a feature which can trip Hyperion **(Confirmed by Roblox employee, Bitdancer)**
> 
>     * Issue is not isolated to Roblox on Linux as some people first thought, both Wine users and Windows users are encountering random crashes
> 
> 
> ## **Some possible fixes/solutions:**
> 
>     * If you are using Bitdefender for your anti-virus provider, **disable "Advanced Threat Defense" or quit out of the application entirely**
> 
>     * **Do not enforce Roblox to use anything other than Automatic** for the rendering mode
> 
>     * **Force the `zavatarteam2` deployment channel,** fixes crashing for Roblox on Linux users, nobody has confirmed if it works with Windows users yet **_(please test this if you can)_**
>       (https://devforum.roblox.com/t/roblox-games-load-for-about-3-seconds-then-instantly-crash/2309871/731?u=waviestballoon)

yep it fixed crashes on nobara 37
vinegar and grapejuice no work well

**Comment by user1126s** [comment] 2023-10-28 17:03
now*

**Comment by n00bslayerxd** [comment] 2023-10-28 17:58
> i don't think data miners have anything to do with a widespread problem that even the developers have acknowledged.

Well, it fixed it for me. I myself didn't even know that would be the thing. I didn't even know I had a virus.

**Comment by Grizzly1706** [comment] 2023-10-29 04:05
> > i don't think data miners have anything to do with a widespread problem that even the developers have acknowledged.
> 
> Well, it fixed it for me. I myself didn't even know that would be the thing. I didn't even know I had a virus.

I just did a scan, after doing a fresh install of windows right before the problem became well known and there aren't any viruses on my PC, yet i'm still having issues with both the regular bootstrapper, and bloxstrap.

**Comment by DragonKillerz** [comment] 2023-10-29 12:47
i still cant use the website version of roblox as of 10/28/2023

**Comment by DragonKillerz** [comment] 2023-10-29 12:53
can you change your channel using bloxstrap

**Comment by Lucas559-noob** [comment] 2023-10-29 17:36
> Linux bootstraper for roblox

that exists? I thought roblox could not run on linux, neither with wine

**Comment by user1126s** [comment] 2023-10-31 15:29
> > Linux bootstraper for roblox
> 
> that exists? I thought roblox could not run on linux, neither with wine

It did not when anticheat released, but 3 months later they made it work again

**Comment by WaviestBalloon** [comment] 2023-10-31 17:46
> can you change your channel using bloxstrap

Yes you can, open the Bloxstrap Menu, click on the **Behaviour** tab and edit this value: 
![image](https://github.com/pizzaboxer/bloxstrap/assets/31796727/f1174b41-a3ee-4328-b54e-2d4fc45f314c)
After that, hit **Save** at the bottom right hand corner.

**Comment by WaviestBalloon** [comment] 2023-10-31 17:52
> > Linux bootstraper for roblox
> 
> that exists? I thought roblox could not run on linux, neither with wine

Roblox on Linux has a rocky history but the people on the client sec team at Roblox do care about Wine/Proton compatability and support, they blocked the compatability layer (Wine and Proton) and virtual machines to ensure telemetry isn't tainted, afterwards the restrictions were lifted.
But before Hyperion was even implemented into the client, Roblox could run on Linux but required some patches by the community, for proper cursor locking/capturing and implementing the `ZwFilterToken` function into Wine.

**Comment by NattoRiisa** [comment] 2023-11-01 14:20
> > ## **Quick recap:**
> > ```
> > * The FastFlag to enforce Vulkan rendering can trip Hyperion **(Confirmed by Roblox employee, Bitdancer)**
> > 
> > * Bitdefender has a feature which can trip Hyperion **(Confirmed by Roblox employee, Bitdancer)**
> > 
> > * Issue is not isolated to Roblox on Linux as some people first thought, both Wine users and Windows users are encountering random crashes
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## **Some possible fixes/solutions:**
> > ```
> > * If you are using Bitdefender for your anti-virus provider, **disable "Advanced Threat Defense" or quit out of the application entirely**
> > 
> > * **Do not enforce Roblox to use anything other than Automatic** for the rendering mode
> > 
> > * **Force the `zavatarteam2` deployment channel,** fixes crashing for Roblox on Linux users, nobody has confirmed if it works with Windows users yet **_(please test this if you can)_**
> >   (https://devforum.roblox.com/t/roblox-games-load-for-about-3-seconds-then-instantly-crash/2309871/731?u=waviestballoon)
> > ```
> 
> yep it fixed crashes on nobara 37 vinegar and grapejuice no work well

win

> ## **Quick recap:**
> * The FastFlag to enforce Vulkan rendering can trip Hyperion **(Confirmed by Roblox employee, Bitdancer)**
> * Bitdefender has a feature which can trip Hyperion **(Confirmed by Roblox employee, Bitdancer)**
> * Issue is not isolated to Roblox on Linux as some people first thought, both Wine users and Windows users are encountering random crashes
> 
> ## **Some possible fixes/solutions:**
> * If you are using Bitdefender for your anti-virus provider, **disable "Advanced Threat Defense" or quit out of the application entirely**
> * **Do not enforce Roblox to use anything other than Automatic** for the rendering mode
> * **Force the `zavatarteam2` deployment channel,** fixes crashing for Roblox on Linux users, nobody has confirmed if it works with Windows users yet **_(please test this if you can)_**
>   (https://devforum.roblox.com/t/roblox-games-load-for-about-3-seconds-then-instantly-crash/2309871/731?u=waviestballoon)

windows user here! does not work!

**Comment by WaviestBalloon** [comment] 2023-11-01 15:42
> windows user here! does not work!

Do you have a Logitech steering wheel at all? Unplug it and start Roblox

**Comment by idioticfool** [comment] 2023-11-01 23:27
> > windows user here! does not work!
> 
> Do you have a Logitech steering wheel at all? Unplug it and start Roblox

although i cannot speak for them, i also use windows and have used the "zavatarteam2" channel (also doesn't work for me sadly) and i don't have a logitech steering wheel and roblox still will not work. even after i have updated it. the only logitech stuff i have is a g502 hero and g635 headset. my only options now are still to either send it to my uncle where he may take a week to see why this is happening or to factory reset my computer. which i do not want to do, due to the fact i have a crap ton of apps i do not remember how i got them and do not want to lose those either, because a majority of them i need.

**Comment by WaviestBalloon** [comment] 2023-11-02 12:16
> although i cannot speak for them, i also use windows and have used the "zavatarteam2" channel (also doesn't work for me sadly) and i don't have a logitech steering wheel and roblox still will not work. even after i have updated it. the only logitech stuff i have is a g502 hero and g635 headset. my only options now are still to either send it to my uncle where he may take a week to see why this is happening or to factory reset my computer. which i do not want to do, due to the fact i have a crap ton of apps i do not remember how i got them and do not want to lose those either, because a majority of them i need.

There is a option to reset without changing or removing your files, although do make sure that there is nothing running that you don't need when launching Roblox, furthermore unplug any hardware like cameras etc making only your keyboard and mouse connected to rule out the possibility of connected hardware leading to the crash.

**Comment by DragonKillerz** [comment] 2023-11-04 04:03
> ###
> [Nov 1, 2023](#issuecomment-1787694877)
there is no channel change thing in 2.5.4
