### ISSUE TITLE
[BUG] graphics setting isnt working

### ISSUE THREAD

**Issue by nigitih** [pizzaboxer/bloxstrap#2827] opened 2024-09-05 16:23 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

i started roblox and my settings are reseted sooo graphics setting that make 21 levels that doesnt working i deleted bloxtrap and roblox than i dowlonded again but its still not working

### Bloxstrap Log

N/A

**Comment by reeddone4** [comment] 2024-09-05 18:06
the fast flag got removed

**Comment by pizzaboxer** [comment] 2024-09-06 22:24
Duplicate of #2812

**Closed by pizzaboxer** 2024-09-06 22:24 UTC
