### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by TryIsHigh** [pizzaboxer/bloxstrap#2005] opened 2024-06-14 23:01 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When i try to open or install bloxstrap a message pops up saying "Bloxstrap does not support running in administrator mode. Relaunch or reinstall Bloxstrap with lower privileges."

**Comment by eat5g** [comment] 2024-06-14 23:02
same thing with me, this didn't happen before. i tried reinstalling but it didn't help

**Comment by cem6161** [comment] 2024-06-14 23:02
they said they will fix it soon.

**Comment by desorz** [comment] 2024-06-14 23:04
i downgraded to v2.5.4 and it works well, just dont use checkbox on "Automatically update Bloxstrap"

**Comment by cem6161** [comment] 2024-06-14 23:05
https://github.com/pizzaboxer/bloxstrap/releases/tag/v2.6.1

**Comment by pizzaboxer** [comment] 2024-06-14 23:21
Duplicate of #2003

**Closed by pizzaboxer** 2024-06-14 23:21 UTC
