### ISSUE TITLE
[BUG] An exception occurred while running Bloxstrap

### ISSUE THREAD

**Issue by Why10Not** [pizzaboxer/bloxstrap#1400] opened 2024-03-05 20:48 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.ComponentModel.Win32Exception: Not enough quota is available to process this command.
[Bloxstrap_20240305T153042Z.log](https://github.com/pizzaboxer/bloxstrap/files/14501364/Bloxstrap_20240305T153042Z.log)

**Comment by pizzaboxer** [comment] 2024-03-06 00:44
Duplicate of #788

**Closed by pizzaboxer** 2024-03-06 00:44 UTC
