### ISSUE TITLE
Roblox crashes

### ISSUE THREAD

**Issue by vanopikss09** [pizzaboxer/bloxstrap#1615] opened 2024-04-13 11:49 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

**When ever I open bloxstrap players from the roblox website the game is loading and then roblox crashes.**

**Comment by pizzaboxer** [comment] 2024-04-13 17:54
Duplicate of #1609

**Closed by pizzaboxer** 2024-04-13 17:54 UTC
