### ISSUE TITLE
BLOXSTRAP WILL NOT WORK PLEASE STOP MAKING ISSUES!!!

### ISSUE THREAD

**Issue by pompompur1nn** [pizzaboxer/bloxstrap#2711] opened 2024-08-21 21:00 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

https://setup.rbxcdn.com/channel/common/version-f0223159583b4054-rbxPkgManifest.txt is 403ing 
![image](https://github.com/user-attachments/assets/5788b742-5053-4dc0-9c9e-a293811b39d9)

**Comment by pizzaboxer** [comment] 2024-08-22 11:06
Duplicate of #2704

**Closed by pizzaboxer** 2024-08-22 11:06 UTC
