### ISSUE TITLE
[REQ] Add an option to remove the multi instance popup

### ISSUE THREAD

**Issue by Chuppa2WasTaken** [pizzaboxer/bloxstrap#2129] opened 2024-06-20 19:10 UTC
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Would be cool if there was an option to hide or remove that popup.
It always closes it when pressing yes when I use my multi instance override app. Regular Roblox works with my multi instance override app, so I know it isn't me.

![image](https://github.com/pizzaboxer/bloxstrap/assets/110486918/d623058a-a21d-42fa-b616-833c81c8b4a9)

**Comment by ilan0098** [comment] 2024-06-20 22:06
It will be toggleable in the next update

**Comment by pizzaboxer** [comment] 2024-06-27 09:33
Duplicate of #2011

**Closed by pizzaboxer** 2024-06-27 09:33 UTC
