### ISSUE TITLE
[BUG] Cannot change installation folder even when i uninstall and reinstall Bloxstrap

### ISSUE THREAD

**Issue by ClocknerTH** [pizzaboxer/bloxstrap#1706] opened 2024-04-29 14:32 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So i've tried reinstalling bloxstrap multiple times after deleting everything, it doesnt work and doesnt give me the Bloxstrap menu where i can select where i want bloxstrap to be installed, the issue with this is it installs itself into a folder of another game, and that games anti cheat doesnt allow me to play that game because bloxstrap installs itself in there.

**Comment by pizzaboxer** [comment] 2024-04-30 07:47
Duplicate of #1705

**Closed by pizzaboxer** 2024-04-30 07:47 UTC
