### ISSUE TITLE
[REQ] Make "Cancel" button Cancellable (same function as X instead) on Modern Bloxstrap bootstrapper

### ISSUE THREAD

**Issue by ohdamisury** [pizzaboxer/bloxstrap#2679] opened 2024-08-17 03:47 UTC
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I have the issues sometimes roblox just wanna launch 2 clients at the same time which is very annoying (not Bloxstrap problem tho) but when i tried to close it the "Cancel" button doesn't seem to work unless im using other bootstrapper like Vista (which has the close button like windows normally does) but those bootstrapper are ugly so maybe implement them to the modern one for better experience.

**Comment by pizzaboxer** [comment] 2024-08-22 22:02
Duplicate of #2662

**Closed by pizzaboxer** 2024-08-22 22:02 UTC
