### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by MlodyDryna** [pizzaboxer/bloxstrap#806] opened 2023-10-24 09:00 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

so... I've got something like this 
![image](https://github.com/pizzaboxer/bloxstrap/assets/145903618/b90e76fc-5727-4d1c-839e-27da1ef25a72)
and idk what to do.

When i try to open roblox it shows the server location but the game window itself doesnt show

(Broken only on version 2.53)

**Comment by pizzaboxer** [comment] 2023-10-24 09:56
Duplicate of #791

**Closed by pizzaboxer** 2023-10-24 09:56 UTC
