### ISSUE TITLE
[BUG] System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by Infraction7** [pizzaboxer/bloxstrap#1001] opened 2023-12-02 16:58 UTC
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

```System.UnauthorizedAccessException: Access to the path 'C:\Users\Антон\AppData\Local\Bloxstrap\Logs' is denied.```
when trying to open bloxstrap.
Recently i changed the name of root of my user and my pc cant find many programs which are using user folder. Any way to fix? I belive its a path problem because i changed username from "Антон" to "Anton"

**Comment by pizzaboxer** [comment] 2023-12-02 23:12
Duplicate of #1000

**Closed by pizzaboxer** 2023-12-02 23:12 UTC
