### ISSUE TITLE
banned for a day and this screen wont go away[BUG] 

### ISSUE THREAD

**Issue by spoopyghostsx** [pizzaboxer/bloxstrap#2478] opened 2024-07-25 04:02 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

i was banned for a day and the screen in my ss wont go away, ive tried uninstalling to manually deletes every file i could find
![image](https://github.com/user-attachments/assets/105a962e-df6e-4176-b83f-dbcade3c603a)

**Comment by pizzaboxer** [comment] 2024-07-28 19:46
Duplicate of #1522

**Closed by pizzaboxer** 2024-07-28 19:46 UTC
