### ISSUE TITLE
[BUG] The Advanced Graphics Quality Selector (AGQS) Suddenly does not work.

### ISSUE THREAD

**Issue by Serty54** [pizzaboxer/bloxstrap#2828] opened 2024-09-05 19:03 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![Screenshot 2024-09-05 215824](https://github.com/user-attachments/assets/6739de51-b1c0-428a-ad95-6c87054ac3a2)
![Screenshot 2024-09-05 215829](https://github.com/user-attachments/assets/b731986e-4283-446f-9f27-05c071062024)
![Screenshot 2024-09-05 215832](https://github.com/user-attachments/assets/e816d546-691b-4e92-b8ad-a4b2cb99acb2)
Here is What happened, I was playing Roblox normally and suddenly a game that mostly does not lag started to run at potato speed, so I opened my setting to see that the graphics has turned to the normal 10 slider and is on level 2 (I have a potato laptop), Note: I did not have these Bloxtrap fastflags I only tried them when I encountered this problem.
 I tried reinstalling Bloxtrap and it still did not want to run the (AGQS), I did see some people also have this can you help?!?!?!?

### Bloxstrap Log

N/A

**Comment by reeddone4** [comment] 2024-09-05 20:08
got removed by roblox

**Comment by D4rkov** [comment] 2024-09-06 08:18
Duplicate of #2825

**Comment by pizzaboxer** [comment] 2024-09-06 22:24
Duplicate of #2812

**Closed by pizzaboxer** 2024-09-06 22:24 UTC
