### ISSUE TITLE
[BUG] keeeps saying error

### ISSUE THREAD

**Issue by larryhowardk** [pizzaboxer/bloxstrap#1827] opened 2024-05-16 19:52 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![wow](https://github.com/pizzaboxer/bloxstrap/assets/169187105/4c398067-a01a-454e-a1ad-f9a533e67732)

**Comment by pizzaboxer** [comment] 2024-05-18 23:33
Duplicate of #1231

**Closed by pizzaboxer** 2024-05-18 23:33 UTC
