### ISSUE TITLE
low fps

### ISSUE THREAD

**Issue by xM4rkHUN** [pizzaboxer/bloxstrap#406] opened 2023-07-20 23:42 UTC
I get lower fps, but I'm not sure why, I don't use any necessary fastflags.

**Comment by pizzaboxer** [comment] 2023-07-21 07:09
Let me see your FastFlag configuration just to be sure.

**Comment by xM4rkHUN** [comment] 2023-07-21 21:50
max fps: 120
lightning technology: chosen by game
escape menu: default
hide GUIs: on
old materials: off
rendering mode: direct3D 11
21 graphics quality selector: off

**Comment by pizzaboxer** [comment] 2023-07-21 23:02
What's your average framerate with and without?

**Comment by xM4rkHUN** [comment] 2023-07-21 23:26
90-120

**Comment by xM4rkHUN** [comment] 2023-07-22 08:41
but i dont know why i get lower fps when lauching the game from the browser

**Comment by pizzaboxer** [comment] 2023-07-22 08:42
Answer the question, I want to get an idea of how much performance you're actually losing, and if it's even caused by Bloxstrap which I doubt it is.

**Comment by xM4rkHUN** [comment] 2023-07-22 08:45
> Answer the question, I want to get an idea of how much performance you're actually losing, and if it's even caused by Bloxstrap which I doubt it is.

okay, 5 mins

**Comment by xM4rkHUN** [comment] 2023-07-22 08:50
when i have these all of 'em off then i get 140-200 fps on 5 graphic bar and 130-150 with full graphic quality.
and with direct3d 11 i get 90-140

**Comment by pizzaboxer** [comment] 2023-07-22 08:52
Only happens when you change your rendering mode to Direct3D?

**Comment by xM4rkHUN** [comment] 2023-07-22 08:53
idrk, i issued that camera delay bug so now idk if this causes, but yes, mostly it takes my fps down

**Comment by pizzaboxer** [comment] 2023-07-22 11:37
Roblox should always be using Direct3D 11 by default if your rendering mode is set to automatic. Set it to automatic again, launch Roblox, and send me the latest log file from %localappdata%\Roblox\logs.

**Comment by xM4rkHUN** [comment] 2023-07-22 12:13
[0.586.0.5860000_20230722T121235Z_Player_F5876_last.log](https://github.com/pizzaboxer/bloxstrap/files/12136441/0.586.0.5860000_20230722T121235Z_Player_F5876_last.log)

**Comment by pizzaboxer** [comment] 2023-07-22 13:46
And you're absolutely sure there's a difference in framerates between force-enabling Direct3D 11 and having it automatically chosen?

**Comment by xM4rkHUN** [comment] 2023-07-22 13:56
yes, but idk why but now i have 60-80

**Comment by xM4rkHUN** [comment] 2023-07-22 13:57
does the fullscreen optimizations give more fps after enabling that in?

**Comment by xM4rkHUN** [comment] 2023-07-22 13:58
i'll try the force again

**Comment by pizzaboxer** [comment] 2023-07-22 13:58
Anyway, I'll close this since it's clear by now that this isn't a problem with Bloxstrap.

**Closed by pizzaboxer** 2023-07-22 13:58 UTC

**Comment by xM4rkHUN** [comment] 2023-07-23 03:44
it fixed, it was because roblox didnt closed
