### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by sp5derr** [pizzaboxer/bloxstrap#826] opened 2023-10-26 04:12 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Bloxstrap Exception 10_25_2023 8_43_03 PM](https://github.com/pizzaboxer/bloxstrap/assets/149035713/7455a1b1-925b-4d11-982c-5a29cbbd6437)

**Comment by IxGamerXL** [comment] 2023-10-26 05:54
Have you tried reinstalling Bloxstrap? I believe the same error was found by another user, and it might help for this case to be included in the wiki's list of common crashes if the absolute solution is to reinstall.

**Comment by pizzaboxer** [comment] 2023-10-26 08:23
Duplicate of #791

**Closed by pizzaboxer** 2023-10-26 08:23 UTC
