### ISSUE TITLE
What should I do if my roblox doesn't start even through Bloxtrap

### ISSUE THREAD

**Issue by Sverlo1337** [pizzaboxer/bloxstrap#2389] opened 2024-07-16 13:20 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Roblox does not start in any way either through Bloxtrap or through a regular launcher, I wrote to roblox support and they did not work in any way, they were talking some nonsense there, well, I launched it through bloxtrap and opened the log and I have the error
"System.InvalidOperationException: The process cannot be started because the file name is not specified." I looked at the wiki, there is no such thing. And I have Windows 7 x64, but my grandmother also has Windows 7 x64 on the same build, everything works, but at home she refuses to work, turned off the antivirus and even before I downloaded it, roblox did not want to start. And I also have roblox appearing in the task manager and loading the processor by 50%, and once again I say that roblox support did not help me in any way, maybe you can help somehow by making some launcher for Windows 7 and so on,

**Comment by NeverLoLSer** [comment] 2024-07-16 13:42
Are you kidding? Install Windows 10 and don't f*** around with the rest of the internet users who have already figured it out

**Comment by pizzaboxer** [comment] 2024-07-28 19:03
Can you send the log file please?

**Comment by Sverlo1337** [comment] 2024-07-29 08:33
If you were referring to the Bloxtrap logs, then here


пн, 29 июл. 2024 г. в 02:03, pizzaboxer ***@***.***>:

**Comment by Sverlo1337** [comment] 2024-07-29 08:50
Even here's a new one for you, I tried to come in today
Here are even the logs of roblox itself

пн, 29 июл. 2024 г. в 02:03, pizzaboxer ***@***.***>:

**Comment by pizzaboxer** [comment] 2024-07-29 09:30
...You still haven't sent anything

**Comment by Sverlo1337** [comment] 2024-07-29 09:34
I sent you the files


пн, 29 июл. 2024 г., 16:30 pizzaboxer ***@***.***>:

**Comment by Sverlo1337** [comment] 2024-07-29 09:37
I sent you the files above

пн, 29 июл. 2024 г., 16:30 pizzaboxer ***@***.***>:

**Comment by pizzaboxer** [comment] 2024-07-29 09:40
There's nothing here.

![image](https://github.com/user-attachments/assets/5cccf865-43c0-4bb3-9889-04cf11005ea1)

Send them directly on GitHub instead of over email. https://github.com/pizzaboxer/bloxstrap/issues/2389

**Comment by Sverlo1337** [comment] 2024-07-29 11:19
[Bloxstrap_20240729T084026Z.log](https://github.com/user-attachments/files/16411775/Bloxstrap_20240729T084026Z.log)
[RobloxPlayerInstaller_4C302.log](https://github.com/user-attachments/files/16411779/RobloxPlayerInstaller_4C302.log)

**Comment by pizzaboxer** [comment] 2024-07-29 16:18
Duplicate of #2315
If you're trying to find out why Roblox isn't launching, see https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

**Closed by pizzaboxer** 2024-07-29 16:18 UTC
