### ISSUE TITLE
Log file is being used by another process error.

### ISSUE THREAD

**Issue by Boi2021Miceoos** [pizzaboxer/bloxstrap#239] opened 2023-05-13 06:39 UTC
I don't know why this occur often, but i found a solution i just delete everything inside the logs & it good to go.
Mind if you fix this error? 
![log file](https://github.com/pizzaboxer/bloxstrap/assets/86916029/201c3e5d-d40b-44b8-9354-7d691886996d)
I know You added to delete old logs file in the new update, but this error still appers.

**Comment by pizzaboxer** [comment] 2023-05-14 12:53
Duplicate of #212. If you find anything new, then please comment there.

**Closed by pizzaboxer** 2023-05-14 12:53 UTC

**Comment by Boi2021Miceoos** [comment] 2023-05-15 07:01
i have no coding experinece yeah
