### ISSUE TITLE
[BUG] Alt +f4, esc doesnt work for a roblox game anymore and graphics quality doesnt uncap

### ISSUE THREAD

**Issue by badmannj** [pizzaboxer/bloxstrap#2918] opened 2024-09-19 21:45 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

 This is making me unable to leave a Roblox game without a task manager, the ESC menu doesn't work as well and doesn't let you see the leaderboard. The maximum graphics quality doesn't work as it is not allowing me to uncap, please I hope these issues will get resolved.

### Bloxstrap Log

N/A

**Comment by moosetwin0** [comment] 2024-09-19 22:13
This is a duplicate of #2911, I recommend closing and talking there.

**Closed** 2024-09-20 16:39 UTC
