### ISSUE TITLE
[BUG] bloxstrap won't let me play roblox

### ISSUE THREAD

**Issue by s0aperstartheyellow** [pizzaboxer/bloxstrap#2707] opened 2024-08-21 20:53 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

bloxstrap how do i fix this
![nooooo](https://github.com/user-attachments/assets/870c8240-9605-4fe7-9146-069d4be9df02)

**Comment by k-awn** [comment] 2024-08-21 20:54
shut up

**Comment by s0aperstartheyellow** [comment] 2024-08-21 20:54
what did i do???

**Comment by pompompur1nn** [comment] 2024-08-21 20:54
https://setup.rbxcdn.com/channel/common/version-f0223159583b4054-rbxPkgManifest.txt got cooked

**Comment by s0aperstartheyellow** [comment] 2024-08-21 20:55
??

**Comment by s0aperstartheyellow** [comment] 2024-08-21 20:55
how do i fix it

**Comment by DiddypartyEnjoyer** [comment] 2024-08-21 20:56
idk lol

**Comment by s0aperstartheyellow** [comment] 2024-08-21 20:56
bruhh how do ur guyses bloxstraps work then???

**Comment by DiddypartyEnjoyer** [comment] 2024-08-21 20:57
who said my bloxstrap works

**Comment by s0aperstartheyellow** [comment] 2024-08-21 20:57
oh

**Comment by Abyxal** [comment] 2024-08-21 20:57
I was playing fine awhile ago, then all of a sudden I can't play no more cause of this error message. It's told me to upgrade my bloxstrap but I'm already on the latest one.

**Comment by s0aperstartheyellow** [comment] 2024-08-21 20:57
dude me too

**Comment by s0aperstartheyellow** [comment] 2024-08-21 20:57
ask a moderator of bloxstrap about this i cant live without roblox

**Comment by DiddypartyEnjoyer** [comment] 2024-08-21 20:57
same

**Comment by DiddypartyEnjoyer** [comment] 2024-08-21 20:58
i might uninstal bloxstrap

**Comment by s0aperstartheyellow** [comment] 2024-08-21 20:58
no, ask a moderator of bloxstrap

**Comment by pizzaboxer** [comment] 2024-08-22 11:06
Duplicate of #2704

**Closed by pizzaboxer** 2024-08-22 11:06 UTC
