### ISSUE TITLE
[BUG] System.Net.Http.HttpRequestException: Response status code does not indicate success: 503 (Service Unavailable). how to fix it 

### ISSUE THREAD

**Issue by mochi990423** [pizzaboxer/bloxstrap#767] opened 2023-10-11 09:15 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 503 (Service Unavailable). how to fix it 
![bloxstrap crashing](https://github.com/pizzaboxer/bloxstrap/assets/147602315/04d84e3b-0533-4025-81e5-71ba1a962480)

**Comment by pizzaboxer** [comment] 2023-10-11 09:49
Duplicate of #786

**Closed by pizzaboxer** 2023-10-11 09:49 UTC
