### ISSUE TITLE
[BUG] Roblox no longer closes when I leave a game

### ISSUE THREAD

**Issue by WindClan** [pizzaboxer/bloxstrap#2214] opened 2024-07-01 02:10 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

It opens the beta app instead of closing like it should
Mainly from kick messages

**Comment by pizzaboxer** [comment] 2024-07-01 05:57
Duplicate of #2049

**Closed by pizzaboxer** 2024-07-01 05:57 UTC
