### ISSUE TITLE
[BUG] Bloxstrap not launching roblox and staying as a background client

### ISSUE THREAD

**Issue by LinBnuuy** [pizzaboxer/bloxstrap#882] opened 2023-11-02 03:45 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I checked the wiki and made sure that roblox bootstrap could run by itself, and it ran perfectly fine without bloxstrap. I checked if Vulkan was enabled, and changed it to automatic and it still had the same issue. I cleared my thumbnail files which didn't solve the problem. I don't have bitdefender at all, and made sure my anti virus bypassed it as a potential virus. Bloxstrap would attempt to launch roblox, crash, and stay as a background client.

**Comment by pizzaboxer** [comment] 2023-11-02 08:18
Can I see the flags you have configured? Also, try forcing a reinstallation through the Behaviour tab in the menu. Enable the option, asve, then try and launch.

**Comment by LinBnuuy** [comment] 2023-11-02 08:49
![flags](https://github.com/pizzaboxer/bloxstrap/assets/149646797/9705cb4f-a416-4c00-8f9c-23860e19651e)

I attempted to force a reinstall through the behavior tab, and it still has the same problem.

**Comment by az20101-re** [comment] 2023-11-02 13:51
same problem here
switching to default roblox isn't an option due to roblox client being stuck on an infinite load and then closing itself.

**Comment by whats37654** [comment] 2023-11-02 15:56
i have the exact same problem

**Comment by TomekHar** [comment] 2023-11-02 18:53
Seems to be an issue with Roblox overall. Vanilla Roblox client refuses to launch with ClientAppSettings file/folder in.

**Comment by pizzaboxer** [comment] 2023-11-03 22:04
caused by the rco flag list lmao

**Closed by pizzaboxer** 2023-11-03 22:04 UTC
