### ISSUE TITLE
[REQ] Allow launching executables that do not have the name "RobloxPlayerBeta.exe"

### ISSUE THREAD

**Issue by YuNoGuy123** [pizzaboxer/bloxstrap#1132] opened 2024-01-15 21:40 UTC
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

When using a modified version of NVidia ANSEL for Roblox, you have to rename the executable name to something else, this is a problem since Bloxstrap only looks for RobloxPlayerBeta.exe since it normally would never be named anything else (which makes sense). You can kinda get around this by using the Custom Integrations tab, but that's obviously not a proper solution. (Plus it would require you to turn off multi-instance launching) 

An option to either set a string that Bloxstrap should look for instead or a direct file path would be greatly appreciated.

**Comment by pizzaboxer** [comment] 2024-01-16 00:11
Duplicate of #997

**Closed by pizzaboxer** 2024-01-16 00:11 UTC
