### ISSUE TITLE
Bloxstrap does not load well! severe malfunction.

### ISSUE THREAD

**Issue by KUNINSYT** [pizzaboxer/bloxstrap#1912] opened 2024-06-02 19:24 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

**Hi I've always used Bloxstrap, and recently it has some serious problems!**

- Lately Bloxstrap is not loading the game well. See the difference between Roblox and Blockstrap:

**Roblox:**
![Screenshot 2024-06-02 220811](https://github.com/pizzaboxer/bloxstrap/assets/160591554/a52465dc-e2b1-434e-9bb0-2533afaff72a)

**Bloxstrap:**
![Screenshot 2024-06-02 220554](https://github.com/pizzaboxer/bloxstrap/assets/160591554/1bb6778b-dddf-4989-8b16-281b678020b5)

**Roblox:**
![Screenshot 2024-06-02 215103](https://github.com/pizzaboxer/bloxstrap/assets/160591554/3a4d252a-8689-4dd6-9fe9-256ab00c0a6d)

**Bloxstrap:**
![Screenshot 2024-06-02 220230](https://github.com/pizzaboxer/bloxstrap/assets/160591554/6345f9be-d5eb-40bd-a4e4-a29c688ef76d)

- **Now it's not like I configured anything in Bloxstrap, I reset the settings to normal, Bloxstrap just crashed fix it urgently!**

It started happening to me a few days ago that Bloxstrap crashes,
Loading problems and more!
And I downloaded the regular roblox, it works better, doesn't crash, no loading problems.
Bloxstrap just doesn't help anymore...

### Blockstrap you must fix this!!!
**The normal Roblox works better for me Blockstrap.**

**Comment by WaviestBalloon** [comment] 2024-06-03 07:54
> Now it's not like I configured anything in Bloxstrap, I reset the settings to normal, Bloxstrap just crashed fix it urgently!

Can you give us a log to work off of?

**Comment by KUNINSYT** [comment] 2024-06-03 08:12
> Can you give us a log to work off of?
I just returned the settings to normal.

**I kind of figured out the problem, since the last Bloxstrap update,
You did something that caused Bloxstrap to not load images properly or limit images per game!**

Bloxstrap:
![Screenshot 2024-06-03 105920](https://github.com/pizzaboxer/bloxstrap/assets/160591554/02a62ce7-2c7a-4e39-806b-d7b848f994bc)

Roblox:
![Screenshot 2024-06-03 110432](https://github.com/pizzaboxer/bloxstrap/assets/160591554/55fd8abc-b8f3-4057-9764-a7fcd393870c)


**All this happened only to me who is the latest update of Bloxstrap,
I don't know what you did but you did something that causes every game to be deleted with multiple images or not loading images well,
And most roleplaying games use the road as an image, police vehicles, and more!

It only happened if it's in a game and if a lot of pictures.**

**Comment by WaviestBalloon** [comment] 2024-06-03 08:15
> You did something that caused Bloxstrap to not load images properly or limit images per game!**

This isn't an issue caused by Bloxstrap unless you're using FastFlags, this seems to be a momentary issue, the graphical issues with textures have already been reported in the Roblox Devforums.
I believe it's related to your graphics card's video memory and how much of it is available.

**Comment by KUNINSYT** [comment] 2024-06-03 08:19
> This isn't an issue caused by Bloxstrap unless you're using FastFlags, this seems to be a momentary issue, the graphical issues with textures have already been reported in the Roblox Devforums. I believe it's related to your graphics card's video memory and how much of it is available.

**But the fact is that it only happened to me when I use Bloxstrap,
The regular Roblox doesn't cause this problem for me.**


This is my FastFlags, do you see a problem here?:
![Screenshot 2024-06-03 111703](https://github.com/pizzaboxer/bloxstrap/assets/160591554/6e88828d-65d2-47f9-88f6-e0ad8b61d747)

**Comment by WaviestBalloon** [comment] 2024-06-03 12:00
> So there are times when he writes "update" and then he puts you into Roblox.

That's Roblox updating, not Bloxstrap.
As you have said that the issue has been solved, please close the Issue as completed.

**Closed** 2024-06-03 17:49 UTC
