### ISSUE TITLE
[REQ] Option to turn off the "Roblox is currently running" prompt

### ISSUE THREAD

**Issue by brokensamsung** [pizzaboxer/bloxstrap#2247] opened 2024-07-05 10:45 UTC
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

While this feature might be convinient, it breaks certain stuff like natro macro. or maybe you just dont want the warning, It would be nice to find a way to disable this, as when the macro tries to rejoin the prompt pops up basically blocking it, and it tries and tries until you stop it 
![obraz](https://github.com/pizzaboxer/bloxstrap/assets/110091682/5683764b-45e1-4745-a927-3ec5cbfc7cc6)
![obraz](https://github.com/pizzaboxer/bloxstrap/assets/110091682/5902a04e-a210-4b94-8784-1d32150072f8)

**Comment by pizzaboxer** [comment] 2024-07-05 19:07
Duplicate of #2011

**Closed by pizzaboxer** 2024-07-05 19:07 UTC
