### ISSUE TITLE
Bloxstrap Exception?

### ISSUE THREAD

**Issue by EpikDudee** [pizzaboxer/bloxstrap#2706] opened 2024-08-21 20:52 UTC
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [x] My answer given in the checkbox above is a lie.

### What problem did you encounter?

idk what does this mean but.. it says this:
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
it said that there is an exception?

**Comment by EpikDudee** [comment] 2024-08-21 20:53
is there any way to fix this?

**Comment by pompompur1nn** [comment] 2024-08-21 20:53
same issue, https://setup.rbxcdn.com/channel/common/version-f0223159583b4054-rbxPkgManifest.txt got cooked

**Comment by pompompur1nn** [comment] 2024-08-21 20:53
no there is no way to fix it until bloxstrap updates

**Comment by EpikDudee** [comment] 2024-08-21 20:54
oh damn, that was a fast reply

**Comment by k-awn** [comment] 2024-08-21 20:54
there are already ten gazillion commnts everyone uses bloxstrap ig

**Comment by EpikDudee** [comment] 2024-08-21 20:55
i guess we have to wait then

**Comment by EpikDudee** [comment] 2024-08-21 20:59
update: bloxstrap is back

**Comment by pizzaboxer** [comment] 2024-08-22 11:06
Duplicate of #2704

**Closed by pizzaboxer** 2024-08-22 11:06 UTC
