### ISSUE TITLE
[BUG] using multi instance with RAM gives the warning at the opening of every instance, even the forst one

### ISSUE THREAD

**Issue by NukeThief** [pizzaboxer/bloxstrap#2100] opened 2024-06-18 16:37 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Basically, BS now has a feature that warns before an instance gets replaced. but it makes multi instance be kinda annoying to use, so please add an optiion to disable that warning.

**Comment by CfwSky** [comment] 2024-06-18 16:49
it will be added in a future update (or you download an unreleased one from actions)

**Comment by pizzaboxer** [comment] 2024-06-27 09:43
Duplicate of #2011

**Closed by pizzaboxer** 2024-06-27 09:43 UTC
