### ISSUE TITLE
[REQ] Allow us to set custom cursor images instead of the 3 presets.

### ISSUE THREAD

**Issue by MrBlueTopHat** [pizzaboxer/bloxstrap#2607] opened 2024-08-09 01:41 UTC
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I have an image for a cursor I would like to use but there is no option in Bloxstrap for me to set it.

**Comment by Roblox-Thot** [comment] 2024-08-09 09:47
PizzaBoxer is planing to make this easier (Source: #1348 )

But for now you can add your own by clicking the "open mods folder" button in the "Mods" tab then going to `content`>`textures`>`Cursors`>`KeyboardMouse` and making two files with the image one called "ArrowFarCursor.png" and the other "ArrowCursor.png"

**Comment by pizzaboxer** [comment] 2024-08-13 20:57
Duplicate of #1348

**Closed by pizzaboxer** 2024-08-13 20:57 UTC
