### ISSUE TITLE
Idek

### ISSUE THREAD

**Issue by l3bronz0** [pizzaboxer/bloxstrap#1907] opened 2024-06-02 05:31 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.InvalidOperationException: 'ContentControl' TargetType does not match type of element 'DataGridColumnFloatingHeader'.

**Comment by pizzaboxer** [comment] 2024-06-08 20:11
Duplicate of #1231

**Closed by pizzaboxer** 2024-06-08 20:11 UTC
