### ISSUE TITLE
Bloxstrap not launching

### ISSUE THREAD

**Issue by wowowowaaaaaaaaa** [pizzaboxer/bloxstrap#2715] opened 2024-08-21 21:01 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/aa5d6314-c5c7-439c-9017-05930a161990)

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

**Comment by pizzaboxer** [comment] 2024-08-22 11:06
Duplicate of #2704

**Closed by pizzaboxer** 2024-08-22 11:06 UTC
