### ISSUE TITLE
(Duplicated post, please go to #2911 instead)

### ISSUE THREAD

**Issue by noideaforausername2000** [pizzaboxer/bloxstrap#2912] opened 2024-09-19 20:08 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![roblox](https://github.com/user-attachments/assets/c088ddaf-f743-4cb3-ae8e-03867d629803)
![roblox2](https://github.com/user-attachments/assets/58934b66-4061-4329-9bea-bad6957f6cb6)

### Bloxstrap Log

N/A

**Comment by FloofyBoiFieldy** [comment] 2024-09-19 20:19
happening to me to

**Comment by moosetwin0** [comment] 2024-09-19 21:05
This is a duplicate of #2911, I recommend closing and talking there.

**Closed** 2024-09-19 21:10 UTC
