### ISSUE TITLE
Bloxstrap crash

### ISSUE THREAD

**Issue by parrole** [pizzaboxer/bloxstrap#2300] opened 2024-07-10 02:08 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

bloxstrap keeps crashing everytime i load it and it wont let me delete it i also cant play roblox because of it. It keeps saying "An  exception has occured while running bloxstrap, heres a pic. 
![image_2024-07-09_220805091](https://github.com/pizzaboxer/bloxstrap/assets/175173707/353e45af-da7f-4d4c-824d-85ae5ffc79a7) 2024-07-10T02:06:25Z [App::OnStartup] Starting Bloxstrap v2.7.0
2024-07-10T02:06:25Z [App::OnStartup] Compiled Tuesday, 9 July 2024 at 2:03:19 PM from commit a7d2a2c3d5af7137804416ba4e5fbdd27bd10f1e (tag/v2.7.0)
2024-07-10T02:06:25Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-07-10T02:06:25Z [LaunchSettings::Parse] Parsing launch arguments
2024-07-10T02:06:25Z [LaunchSettings::Parse] Parsing launch flags
2024-07-10T02:06:25Z [LaunchSettings::ParseFlag] Started with IsMenuLaunch flag
2024-07-10T02:06:25Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-07-10T02:06:26Z [JsonManager<Settings>::Load] Loaded successfully!
2024-07-10T02:06:26Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-07-10T02:06:26Z [JsonManager<State>::Load] Loaded successfully!
2024-07-10T02:06:26Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-07-10T02:06:26Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2024-07-10T02:06:26Z [FastFlagManager::SetValue] Changing of 'FFlagHandleAltEnterFullscreenManually' from 'False' to 'False' is pending
2024-07-10T02:06:26Z [RobloxDeployment::TestConnection.https://setup.rbxcdn.com] Connecting...
2024-07-10T02:06:26Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-07-10T02:06:26Z [RobloxDeployment::InitializeConnectivity] Testing connectivity...
2024-07-10T02:06:28Z [RobloxDeployment::TestConnection.https://roblox-setup.cachefly.net] Connecting...
2024-07-10T02:06:28Z [HttpClientLoggingHandler::ProcessRequest] GET https://roblox-setup.cachefly.net/version
2024-07-10T02:06:28Z [RobloxDeployment::TestConnection.https://setup-ak.rbxcdn.com] Connecting...
2024-07-10T02:06:28Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup-ak.rbxcdn.com/version
2024-07-10T02:06:30Z [RobloxDeployment::TestConnection.https://s3.amazonaws.com/setup.roblox.com] Connecting...
2024-07-10T02:06:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://s3.amazonaws.com/setup.roblox.com/version
2024-07-10T02:06:56Z [RobloxDeployment::TestConnection.https://setup.rbxcdn.com] System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.RobloxDeployment.TestConnection(String url, Int32 priority)
2024-07-10T02:06:56Z [App::GlobalExceptionHandler] An exception occurred
2024-07-10T02:06:56Z [App::FinalizeExceptionHandling] System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.RobloxDeployment.TestConnection(String url, Int32 priority)
   at Bloxstrap.RobloxDeployment.InitializeConnectivity()
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024-07-10T02:06:58Z [RobloxDeployment::TestConnection.https://setup-ak.rbxcdn.com] System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.RobloxDeployment.TestConnection(String url, Int32 priority)
2024-07-10T02:06:58Z [RobloxDeployment::TestConnection.https://roblox-setup.cachefly.net] System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.RobloxDeployment.TestConnection(String url, Int32 priority)
2024-07-10T02:07:00Z [RobloxDeployment::TestConnection.https://s3.amazonaws.com/setup.roblox.com] System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.RobloxDeployment.TestConnection(String url, Int32 priority)

**Comment by pizzaboxer** [comment] 2024-07-10 06:35
Duplicate of #2294

**Closed by pizzaboxer** 2024-07-10 06:35 UTC
