### ISSUE TITLE
I can back new menu on RBLX

### ISSUE THREAD

**Issue by NikSavchenk0** [pizzaboxer/bloxstrap#140] opened 2023-04-16 16:36 UTC
I can get a new menu, I just really liked it but later it was removed in 2021, but then it came back again just can I still get it?
![image-3](https://user-images.githubusercontent.com/58150480/232326982-ff7dc9c3-c6b3-4e97-97d4-c841ecfc8a82.png)
![image-4](https://user-images.githubusercontent.com/58150480/232327024-52b9c41b-f911-49f5-9560-352fb8e199fe.png)

**Comment by EasternBloxxer** [comment] 2023-04-16 18:39
wdym?

**Comment by pizzaboxer** [comment] 2023-04-16 18:41
This is coming soon, see #125. I'm gonna close this since this is more or less a duplicate of that.

**Closed by pizzaboxer** 2023-04-16 18:41 UTC

**Comment by NikSavchenk0** [comment] 2023-04-18 21:34
https://devforum.roblox.com/t/how-to-test-the-new-in-game-menu/573380/37
