### ISSUE TITLE
Autoclicker not working

### ISSUE THREAD

**Issue by RealDaylin** [pizzaboxer/bloxstrap#604] opened 2023-08-27 13:43 UTC
uhh can someone tell me

**Comment by pizzaboxer** [comment] 2023-08-27 13:54
Duplicate of #601. Though, you should at least check to see if it happens without Bloxstrap. If it does, then there's nothing I can do anyway.

https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Closed by pizzaboxer** 2023-08-27 13:54 UTC
