### ISSUE TITLE
Bloxstrap does not support running in administrator mode. Relaunch or reinstall Bloxstrap with lower permissions. [BUG] 

### ISSUE THREAD

**Issue by bruhallusernamesaretaken** [pizzaboxer/bloxstrap#2009] opened 2024-06-14 23:11 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I tried playing Roblox with Bloxstrap but its giving me this error every time I try to launch I even installed the newest version of Bloxstrap and still get the same error I even tried installing it with nothing changed in Bloxstrap but with no difference, I've tried with just the regular Roblox and it works perfectly fine. I have not changed or run Bloxstrap in administrator mode but this has popped up. 
![image_2024-06-14_161134298](https://github.com/pizzaboxer/bloxstrap/assets/106092543/96a3294f-7133-4321-9334-447aecb7daaa)

**Comment by pizzaboxer** [comment] 2024-06-14 23:21
Duplicate of #2003

**Closed by pizzaboxer** 2024-06-14 23:21 UTC
