### ISSUE TITLE
[BUG] it says "System.ComponentModel.Win32Exception: Cuota insuficiente para procesar este comando." and dont mind it being spanish.

### ISSUE THREAD

**Issue by MyRulesMyStyle** [pizzaboxer/bloxstrap#1429] opened 2024-03-11 00:52 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

most of the time i go to bloxstrap normally but when i alt enter when im in a game then quit and go to system tray B.S. gives me this error :c

**Comment by pizzaboxer** [comment] 2024-03-11 17:18
Duplicate of #788

**Closed by pizzaboxer** 2024-03-11 17:18 UTC
