### ISSUE TITLE
[REQ] Fastflag profiles

### ISSUE THREAD

**Issue by JoaoTeco10** [pizzaboxer/bloxstrap#2891] opened 2024-09-14 18:53 UTC
### Acknowledgement of preliminary instructions

- [x] I have read and acknowledged the preliminary instructions.

### What idea do you have?

In the fastflags tab, add an option to create fastflag profiles, which would allow people to save enabled fastflags  then switch to another profile with other fastflags

Sorry if it's hard to understand, my english isn't good

**Comment by pizzaboxer** [comment] 2024-09-15 17:35
Duplicate of #1098

**Closed by pizzaboxer** 2024-09-15 17:35 UTC
