### ISSUE TITLE
[REQ] confirm launch

### ISSUE THREAD

**Issue by jamesgarry1** [pizzaboxer/bloxstrap#1885] opened 2024-05-30 17:20 UTC
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

require confirmation from the user to launch "play roblox" to avoid misclicking and closing a already existing instance of roblox

**Comment by pizzaboxer** [comment] 2024-06-08 20:18
Duplicate of #606

**Closed by pizzaboxer** 2024-06-08 20:18 UTC
