### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by davidverho** [pizzaboxer/bloxstrap#1937] opened 2024-06-09 04:05 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

so i tried to open bloxstrap but when i opened it, it did not open roblox i have uninstalled and reinstalled and everything

**Comment by pizzaboxer** [comment] 2024-06-09 08:45
So what did it do? What did it open?

**Comment by fl8tio** [comment] 2024-06-09 13:39
@pizzaboxer the issue is with msi afterburner with riva tuner, after i closed it my bloxstrap worked perfectly, idk if its because its outdated or what. I made an account purely to say this.

**Comment by AmateurProgrammerishere** [comment] 2024-06-14 22:27
> @pizzaboxer the issue is with msi afterburner with riva tuner, after i closed it my bloxstrap worked perfectly, idk if its because its outdated or what. I made an account purely to say this.

well this is roblox fault not pizzaboxer an anti cheat called byfron block these programs.

**Comment by pizzaboxer** [comment] 2024-07-29 16:34
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Closed by pizzaboxer** 2024-07-29 16:34 UTC
