### ISSUE TITLE
[BUG] Using Version 2 escape menu will automatically switch to Version 1 Escape menu

### ISSUE THREAD

**Issue by The69thElement** [pizzaboxer/bloxstrap#2724] opened 2024-08-22 14:18 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I normally use Version 2 Escape menu, however today it suddenly swapped to Version 1 despite me not touching Bloxstrap whatsoever, and when I use either Version 4 or Version 1 Menu they display correctly but only Version 2 got swapped by Version 1

**Comment by pizzaboxer** [comment] 2024-08-22 22:20
Duplicate of #2718

**Closed by pizzaboxer** 2024-08-22 22:20 UTC
