### ISSUE TITLE
Unapproved 3rd party app message [BUG] 

### ISSUE THREAD

**Issue by Gooter64** [pizzaboxer/bloxstrap#814] opened 2023-10-25 19:36 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

roblox keeps detecting bloxstrap and not letting me use it

![image](https://github.com/pizzaboxer/bloxstrap/assets/76504156/b5c5d96a-c72b-4083-b175-d8d5c65c1fb6)

**Comment by PrivateDataStorage** [comment] 2023-10-25 19:42
this isn't bloxstrap. this is possibly a different third party application. Try doing a clean boot with bloxstrap enabled,

[perform a clean boot](https://www.bing.com/ck/a?!&&p=cf3b7dfd264c3d49JmltdHM9MTY5ODE5MjAwMCZpZ3VpZD0yODRhNzM5Ny03OGU0LTY3M2EtMjcxYi02MTcyNzk0ZTY2NDYmaW5zaWQ9NTIwMA&ptn=3&hsh=3&fclid=284a7397-78e4-673a-271b-6172794e6646&psq=clean+startup+windows+10&u=a1aHR0cHM6Ly9zdXBwb3J0Lm1pY3Jvc29mdC5jb20vZW4tdXMvdG9waWMvaG93LXRvLXBlcmZvcm0tYS1jbGVhbi1ib290LWluLXdpbmRvd3MtZGEyZjk1NzMtNmVlYy0wMGFkLTJmOGEtYTk3YTE4MDdmM2Rk&ntb=1)

**Comment by pizzaboxer** [comment] 2023-10-25 21:04
Duplicate of #774

**Closed by pizzaboxer** 2023-10-25 21:04 UTC
