### ISSUE TITLE
[BUG] CANT RUN SO IM RUNNING AND IT SAYS ERROR CAN DO THAT  IT SAYS System.IO.IOException: The file 'C:\Users\user\AppData\Local\Bloxstrap\Modifications\content\fonts\CustomFont.ttf' already exists.

### ISSUE THREAD

**Issue by XWATERMELONSTEP** [pizzaboxer/bloxstrap#1807] opened 2024-05-13 15:11 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/169687340/01594a38-5207-4e3c-8f4e-d3c05b753076)

**Comment by pizzaboxer** [comment] 2024-05-13 21:53
Known bug. When you're installing Bloxstrap, don't choose a custom font. Choose it after installation.

**Comment by pizzaboxer** [comment] 2024-06-08 21:33
Duplicate of #1658

**Closed by pizzaboxer** 2024-06-08 21:33 UTC
Labels: bug
