### ISSUE TITLE
[BUG] Bloxstrap won't install, I got a new PC but it still isn't installing

### ISSUE THREAD

**Issue by realeagleFR** [pizzaboxer/bloxstrap#2295] opened 2024-07-09 22:37 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I'm *very* confused. 
Here is my log:
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.

[Inner Exception]
System.TimeoutException: A task was canceled.

[Inner Exception]
System.Threading.Tasks.TaskCanceledException: A task was canceled.

**Comment by pizzaboxer** [comment] 2024-07-10 06:32
Duplicate of #2294

**Closed by pizzaboxer** 2024-07-10 06:32 UTC
