### ISSUE TITLE
[BUG] Am stuck on the banned for one day screen

### ISSUE THREAD

**Issue by St1zzy1** [pizzaboxer/bloxstrap#2409] opened 2024-07-17 13:11 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I was banned for a day and then when i load up bloxstrap am stuck on the banned screen and cant do nothing but i can play then game on normal roblox launcher and my phone but on bloxstrap am stuck on that screen and doesnt let me do nothing and i tried reinstalling and everything but it shows always the same screen
![image_2024-07-17_151048676](https://github.com/user-attachments/assets/22f898c9-5b19-460a-807e-4c28f4c4fbd8)

**Comment by St1zzy1** [comment] 2024-07-17 13:55
i tried that to but it didnt work for me so idk what to do

**Comment by St1zzy1** [comment] 2024-07-17 14:57
i fixed it just had to delete the robloxsettings in appdata

**Comment by ShadowCodeX-debug** [comment] 2024-07-18 14:02
Tbh I can imagine Roblox suddenly enforce their bootstrapper.

**Comment by pizzaboxer** [comment] 2024-07-28 19:09
Duplicate of #1522

**Closed** 2024-07-28 19:09 UTC

**Comment by Vxmpirx** [comment] 2024-10-26 07:54
> i fixed it just had to delete the robloxsettings in appdata

PLSSSSSSSSS I BEG OF YOU TELL ME HOWWOWOWW
