### ISSUE TITLE
[BUG] whenever i get banned for talking to people in a very "good" way i can't log out

### ISSUE THREAD

**Issue by har3nz** [pizzaboxer/bloxstrap#2307] opened 2024-07-10 14:12 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

title please fix :)

**Comment by pizzaboxer** [comment] 2024-07-11 05:19
Duplicate of #1522

**Closed by pizzaboxer** 2024-07-11 05:19 UTC
