### ISSUE TITLE
[BUG] When leaving a game getting an error message

### ISSUE THREAD

**Issue by BetterAxel** [pizzaboxer/bloxstrap#1965] opened 2024-06-13 17:30 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Screenshot 2024-06-13 122841](https://github.com/pizzaboxer/bloxstrap/assets/172632207/829c6662-98ff-4278-9770-db45aa88727b)

**Comment by pizzaboxer** [comment] 2024-06-14 12:55
Duplicate of #1175. Disable the option to disable the desktop app for now.

**Closed by pizzaboxer** 2024-06-14 12:55 UTC
