### ISSUE TITLE
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

### ISSUE THREAD

**Issue by n4bsssss** [pizzaboxer/bloxstrap#2708] opened 2024-08-21 20:54 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

when i try run roblox i get this error log message i do not know what to do.
![Screenshot (208)](https://github.com/user-attachments/assets/4f0a4117-2331-4e54-8613-4e7883202870)

**Comment by Abyxal** [comment] 2024-08-21 20:56
I too have the same problem, and I have the latest bloxstrap.

**Comment by jake7553562** [comment] 2024-08-21 20:56
i am also getting this problem, and i have the latest version too.

**Comment by DebenTorba** [comment] 2024-08-21 20:57
Same here

**Comment by Abyxal** [comment] 2024-08-21 20:58
I guess we just have to wait for Bloxstrap to update, I'm just gonna uninstall Bloxstrap until its fixed or there's a solution.

**Comment by 1byy1** [comment] 2024-08-21 20:59
its fixed

**Comment by hellohihowisyourday** [comment] 2024-08-21 21:00
yay

**Comment by lestmonroe** [comment] 2024-08-21 21:02
im also have this problem, it was working at 5 am this morning, and i went to bed and woke up now, at 5 pm and i get this error

**Comment by pizzaboxer** [comment] 2024-08-22 11:06
Duplicate of #2704

**Closed by pizzaboxer** 2024-08-22 11:06 UTC
