### ISSUE TITLE
[BUG] Bloxstrap advanced graphics quality issue

### ISSUE THREAD

**Issue by 120hzTTVzenq** [pizzaboxer/bloxstrap#2825] opened 2024-09-05 13:09 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I have the advanced quality selector ticked on for my bloxstrap but for some reason when I join a game it is still stuck at the regular 10 graphics quality selector.

### Bloxstrap Log

N/A

**Comment by BMaadaaa** [comment] 2024-09-05 13:28
I also experienced that, after updating to the latest version

**Comment by jaKub7781** [comment] 2024-09-05 13:30
**same**, posted this to reddit

**Comment by NabHeyka22** [comment] 2024-09-05 13:31
fflag is no longer available
except this option to be gone in the next update of bloxstrap

**Comment by jaKub7781** [comment] 2024-09-05 13:33
> fflag is no longer available except this option to be gone in the next update of bloxstrap

yeah, i should disable fflags.

**Comment by jaKub7781** [comment] 2024-09-05 13:35
you guys should try resetting the bloxstrap settings to default.

this can sometimes resolve issues caused by incorrect configurations.
if not, **turn it off.**

**Comment by Zacgamingpro1234** [comment] 2024-09-05 15:35
Roblox removed this fflag and it will be removed in the next bloxstrap released, you should close this issue.

**Comment by reeddone4** [comment] 2024-09-05 18:06
^^

**Comment by Serty54** [comment] 2024-09-05 19:05
> you guys should try resetting the bloxstrap settings to default.
> 
> this can sometimes resolve issues caused by incorrect configurations. if not, **turn it off.**

I tried everything

**Comment by Serty54** [comment] 2024-09-05 19:06
I also have this problem and posted it but why would you want to disable such a feature?

**Comment by Zacgamingpro1234** [comment] 2024-09-06 08:01
> I also have this problem and posted it but why would you want to disable such a feature?

Ik I wouldn't remove it but since roblox has you can't do it anymore.

**Comment by D4rkov** [comment] 2024-09-06 08:24
Is there another way to increase render distance now that 21 graphics quality selector is gone?

**Comment by Storm-930** [comment] 2024-09-06 08:31
You know that the "21 graphics" is really just graphics level 10 right

**Comment by D4rkov** [comment] 2024-09-06 09:06
> You know that the "21 graphics" is really just graphics level 10 right

Not rly, it had longer render distance than 10.

**Comment by NabHeyka22** [comment] 2024-09-06 09:12
no it doesn't
that's just you thinking that

**Comment by D4rkov** [comment] 2024-09-06 09:35
> no it doesn't that's just you thinking that

I literally compared with both settings, it's not "Thinking" it was visually confirmed. The map rendered further but it was not detailed, just the ground basically loaded in, probs cause of Streaming Enabled. It rendered farther but didn't load details.

**Comment by NabHeyka22** [comment] 2024-09-06 09:39
confirmed by who

**Comment by Toibidien191** [comment] 2024-09-06 13:16
for some reason, bloxstrap does not working (i tried using fps unlocker on bloxstrap but its still using roblox's fps unlocker)

**Comment by NabHeyka22** [comment] 2024-09-06 13:21
open a issue either on the discord server or in here

**Comment by spokeys06** [comment] 2024-09-06 17:30
so the 21 graphics configured gone? or it a bug

**Comment by wendingos** [comment] 2024-09-06 20:38
same

**Comment by pizzaboxer** [comment] 2024-09-06 22:21
Duplicate of #2812

**Closed by pizzaboxer** 2024-09-06 22:21 UTC

**Comment by asIaveofallah** [comment] 2024-09-08 02:03
Im alos having this issue. I loaded up Roblox, and it randomly stopped working. Ive delted bloxstrap, and roblox like 5 times, and retried, and it never worked. I restarted my pc, and tried on different account, and it still didnt work. I also put my settings to default, and it still didnt work.

**Comment by Zacgamingpro1234** [comment] 2024-09-08 14:53
> Im alos having this issue

Roblox removed the ability to do this so its impossible unless Roblox readds it.
